Renaming hub to hubctl epam/hubctl#22

diff --git a/bin/ask b/bin/ask
--- a/bin/ask
+++ b/bin/ask
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 # Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
@@ -12,6 +12,16 @@ enabled="$priority"
 ask="suggested hubstate random history default env empty"
 brief=""
 message=""
+
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
 
 usage() {
   cat << EOF
@@ -260,7 +270,7 @@ for hint in $priority; do
       hint_val="$(dotenv -f "$HISTORY_FILE" get "$ENV")"
     ;;
     "hubstate" )
-      hint_val=$(hub show -q ".parameters.$PARAM" -- -rM 2>/dev/null || echo "")
+      hint_val=$($hubctl show -q ".parameters.$PARAM" -- -rM 2>/dev/null || echo "")
     ;;
     "random" )
       hint_val="$(uuidgen | tr '[:upper:]' '[:lower:]' | tr -d -)"
diff --git a/hub-stack-backup-create b/hub-stack-backup-create
--- a/hub-stack-backup-create
+++ b/hub-stack-backup-create
@@ -12,17 +12,28 @@ HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
 PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
 export PATH
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 usage() {
 cat << EOF
 
 Create backup for current stack
 
 Usage:
-$ hub stack backup create
+$ hubctl stack backup create
 
 Creates a backup for entire stack
 
-$  hub stack backup create -c component1,component2
+$  hubctl stack backup create -c component1,component2
 
 Creates a backup for two components
 
@@ -30,9 +41,9 @@ Parameters:
     -t --tag              Backup tags
     -c --component        Components to backup
     -V  --verbose         Verbose outputs for debug purpose
-    --tty                 Use TTY (terminal) mode for hub ${verb}
-    --no-tty              Do not use TTY (terminal) mode for hub ${verb}
-    --                    Separator to define "hub ${verb}" low level parameters (see: "hub ${verb} --help")
+    --tty                 Use TTY (terminal) mode for hubctl ${verb}
+    --no-tty              Do not use TTY (terminal) mode for hubctl ${verb}
+    --                    Separator to define "hubctl ${verb}" low level parameters (see: "hubctl ${verb} --help")
     -h  --help            Print this message
 
 EOF
@@ -100,7 +111,7 @@ fi
 if test -z "$HUB_STATE"; then
   HUB_STATE=".hub/$HUB_DOMAIN_NAME.state"
 fi
-echo "* Using hub state:"
+echo "* Using hubctl state:"
 for i in ${HUB_STATE//,/ }; do
   echo "  - $i"
 done
@@ -108,7 +119,7 @@ done
 if test -z "$HUB_ELABORATE"; then
   HUB_ELABORATE=".hub/$HUB_DOMAIN_NAME.elaborate"
 fi
-echo "* Using hub elaborate:"
+echo "* Using hubctl elaborate:"
 for i in ${HUB_ELABORATE//,/ }; do
   echo "  - $i"
   if ! grep :// <<<$i >/dev/null; then
@@ -128,7 +139,7 @@ if $FULL_STACK || test -n "$HUB_ELABORATE_FILE" -a ! -e "$HUB_ELABORATE_FILE"; t
 elif test -n "$HUB_ELABORATE_FILE"; then
   if ! "$script_dir"/check-elaborate "$HUB_ELABORATE_FILE" "$HUB_FILES"; then
     echo "Call:"
-    echo "    $ hub stack elaborate"
+    echo "    $ hubctl stack elaborate"
     echo "or update elaborate file timestamp:"
     echo "    $ touch $HUB_ELABORATE_FILE"
     echo
@@ -160,12 +171,12 @@ trap "rm_empty $HUB_BACKUP_DIR" EXIT
 cat << EOF
 * Running CLI command:
 
-  $ hub backup create $HUB_ELABORATE -s $HUB_STATE -o $HUB_BACKUP_DIR/hub-bundle.yaml.gz $HUB_OPTS
+  $ hubctl backup create $HUB_ELABORATE -s $HUB_STATE -o $HUB_BACKUP_DIR/hub-bundle.yaml.gz $HUB_OPTS
 
 EOF
 
 # shellcheck disable=SC2086
-hub backup create "$HUB_ELABORATE" -s "$HUB_STATE" -o "$HUB_BACKUP_DIR/hub-bundle.yaml.gz" $HUB_OPTS
+$hubctl backup create "$HUB_ELABORATE" -s "$HUB_STATE" -o "$HUB_BACKUP_DIR/hub-bundle.yaml.gz" $HUB_OPTS
 
 if test -n "$HUB_BACKUP_TAG"; then
   echo "* Tagging backup: $HUB_BACKUP_TAG"
diff --git a/hub-stack-backup-elaborate b/hub-stack-backup-elaborate
--- a/hub-stack-backup-elaborate
+++ b/hub-stack-backup-elaborate
@@ -12,25 +12,36 @@ HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
 PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
 export PATH
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 usage() {
 cat << EOF
 
 Elaborate (include) backup parameters with the stack parameters
 
 Usage:
-$ hub stack backup elaborate BACKUP_NAME/TAG
+$ hubctl stack backup elaborate BACKUP_NAME/TAG
 
 Parameters:
     -V  --verbose         Verbose outputs for debug purpose
-    --tty                 Use TTY (terminal) mode for hub ${verb}
-    --no-tty              Do not use TTY (terminal) mode for hub ${verb}
-    --                    additional arguments for "hub backup unbundle" command
+    --tty                 Use TTY (terminal) mode for hubctl ${verb}
+    --no-tty              Do not use TTY (terminal) mode for hubctl ${verb}
+    --                    additional arguments for "hubctl backup unbundle" command
     -h  --help            Print this message
 
-Additional arguments for: hub backup unbundle -h
+Additional arguments for: hubctl backup unbundle -h
 ---
 EOF
-  hub backup unbundle -h
+  $hubctl backup unbundle -h
 }
 
 
@@ -126,15 +137,15 @@ fi
 cat <<EOF
 * Running CLI command:
 
-  $ hub backup unbundle $HUB_OPTS -o $backup_path/params.yaml.gz
+  $ hubctl backup unbundle $HUB_OPTS -o $backup_path/params.yaml.gz
 
 EOF
 
 # shellcheck disable=SC2086
-hub backup unbundle $HUB_OPTS -o "$backup_path/params.yaml.gz"
+$hubctl backup unbundle $HUB_OPTS -o "$backup_path/params.yaml.gz"
 gunzip -c "$backup_path/params.yaml.gz" > "$backup_path/params.yaml"
 
-hub stack elaborate --hub-files "$HUB_FILES $backup_path/params.yaml"
+$hubctl stack elaborate --hub-files "$HUB_FILES $backup_path/params.yaml"
 echo "Updating $HUB_BACKUP_DIR/$HUB_DOMAIN_NAME/.elaborate"
 if test -L "$HUB_BACKUP_DIR/$HUB_DOMAIN_NAME/.elaborate"; then
   unlink "$HUB_BACKUP_DIR/$HUB_DOMAIN_NAME/.elaborate"
diff --git a/hub-stack-deploy b/hub-stack-deploy
--- a/hub-stack-deploy
+++ b/hub-stack-deploy
@@ -16,6 +16,17 @@ export PATH HUB_WORKDIR
 DOT_ENV="$(files abspath .env)"
 export DOT_ENV
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 verb=deploy/undeploy
 
 usage() {
@@ -39,9 +50,9 @@ Parameters:
     -l --limit            Component to stop ${verb} at
     --profile             Deployment profile, one of: local, toolbox, pod
     -V  --verbose         Verbose outputs for debug purpose
-    --tty                 Use TTY (terminal) mode for hub ${verb}
-    --no-tty              Do not use TTY (terminal) mode for hub ${verb}
-    --                    Separator to define "hub ${verb}" low level parameters (see: "hub ${verb} --help")
+    --tty                 Use TTY (terminal) mode for hubctl ${verb}
+    --no-tty              Do not use TTY (terminal) mode for hubctl ${verb}
+    --                    Separator to define "hubctl ${verb}" low level parameters (see: "hubctl ${verb} --help")
     -h  --help            Print this message
 
 EOF
@@ -98,7 +109,7 @@ while test "$1" != ""; do
 done
 
 finalize() {
-  status="$(hub show -- '.status.status')"
+  status="$($hubctl show -- '.status.status')"
   echo -n "Deployment status: "
   if test "$1" = "0"; then
 cat << EOF | color green
@@ -126,10 +137,10 @@ cat << EOF
 Stack configuration (.env)
 
 To resolve please run:
-  $ hub configure -f hub.yaml
+  $ hubctl configure -f hub.yaml
 
 To explore more configuration options:
-  $ hub configure -f hub.yaml --help
+  $ hubctl configure -f hub.yaml --help
 
 EOF
   exit 1
@@ -137,15 +148,15 @@ fi
 
 if test -z "$HUB_FILES"; then
   cat << EOF
-Error: cannot find hub definition files (HUB_FILES) in .env"
+Error: cannot find hubctl definition files (HUB_FILES) in .env"
 
 Probably because stack has not been initialized for deployment yet!
 
 Example:
-  $ hub stack init -f hub.yaml
+  $ hubctl stack init -f hub.yaml
 
 To explore more configuration options:
-  $ hub stack init -f hub.yaml --help
+  $ hubctl stack init -f hub.yaml --help
 
 EOF
 
@@ -154,7 +165,7 @@ fi
 
 if test "$HUB_AUTOCONFIGURE" = "1"; then
   echo -n "Proceeding with:"; color h "configure"
-  hub stack configure "$(test "$VERBOSE" = "true" && echo "--verbose")"
+  $hubctl stack configure "$(test "$VERBOSE" = "true" && echo "--verbose")"
   echo "Reloading .env file"
   eval "$(dotenv -f $HUB_WORKDIR/.env "export")"
   echo -n "Proceeding with:"; color h "$verb"
@@ -166,15 +177,15 @@ fi
 
 if test -z "$HUB_DOMAIN_NAME"; then
 cat << EOF
-Error: cannot find hub definition files (HUB_DOMAIN_NAME) in .env"
+Error: cannot find hubctl definition files (HUB_DOMAIN_NAME) in .env"
 
 Probably because stack has not been configured for deployment yet!
 
 Example:
-  $ hub stack configure
+  $ hubctl stack configure
 
 To explore more configuration options:
-  $ hub stack configure --help
+  $ hubctl stack configure --help
 
 EOF
 
@@ -200,7 +211,7 @@ HUB=${HUB:-hub}
 if test -z "$HUB_STATE"; then
   HUB_STATE=".hub/$HUB_DOMAIN_NAME.state"
 fi
-echo "* Using hub state:"
+echo "* Using hubctl state:"
 for i in ${HUB_STATE//,/ }; do
   echo "  - $i"
 done
@@ -208,7 +219,7 @@ done
 if test -z "$HUB_ELABORATE"; then
   HUB_ELABORATE=".hub/$HUB_DOMAIN_NAME.elaborate"
 fi
-echo "* Using hub elaborate:"
+echo "* Using hubctl elaborate:"
 for i in ${HUB_ELABORATE//,/ }; do
   echo "  - $i"
   if ! grep :// <<<$i >/dev/null; then
@@ -227,7 +238,7 @@ elif test -n "$HUB_ELABORATE_FILE"; then
   if ! check-elaborate "$HUB_ELABORATE_FILE" "$HUB_FILES"; then
     if test -z "$HUB_MANUAL_ELABORATE"; then
       echo    "Run this command:"
-      color h "    hub stack elaborate"
+      color h "    hubctl stack elaborate"
       echo    "or update elaborate file timestamp:"
       echo    "    touch $HUB_ELABORATE_FILE"
       echo
@@ -271,7 +282,7 @@ Proceeding with: ${verb}
 * Using profile: $HUB_DEPLOY_PROFILE
 * Running CLI command:
 
-  $ hub ${verb} $HUB_ELABORATE -s $HUB_STATE $HUB_OPTS
+  $ hubctl ${verb} $HUB_ELABORATE -s $HUB_STATE $HUB_OPTS
 
 EOF
 
diff --git a/hub-stack-explain b/hub-stack-explain
--- a/hub-stack-explain
+++ b/hub-stack-explain
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 # Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
@@ -29,6 +29,17 @@ Parameters:
 EOF
 }
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 HUB_OPTS=
 while [ "$1" != "" ]; do
     case $1 in
@@ -48,4 +59,4 @@ if test ! -f .env; then
 fi
 eval "$(dotenv export -f "$HUB_WORKDIR/.env" )"
 
-hub explain "$HUB_ELABORATE" "$HUB_STATE" $HUB_OPTS | less -R
+$hubctl explain "$HUB_ELABORATE" "$HUB_STATE" $HUB_OPTS | less -R
diff --git a/hub-stack-invoke b/hub-stack-invoke
--- a/hub-stack-invoke
+++ b/hub-stack-invoke
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 # Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
@@ -12,13 +12,24 @@ HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
 PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
 export PATH
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 usage() {
 cat << EOF
 
 Invoke stack component's verb
 
 Usage:
-$ hub stack invoke <component> <verb>
+$ hubctl stack invoke <component> <verb>
 
 Parameters:
     -V  --verbose          Verbose outputs for debug purpose
@@ -65,4 +76,4 @@ elif test -n "$KUBECONFIG" -a -f "$KUBECONFIG"; then
 fi
 
 # shellcheck disable=SC2086
-hub invoke -m "$HUB_ELABORATE" -s "$HUB_STATE" $HUB_OPTS
+$hubctl invoke -m "$HUB_ELABORATE" -s "$HUB_STATE" $HUB_OPTS
diff --git a/hub-stack-ls b/hub-stack-ls
--- a/hub-stack-ls
+++ b/hub-stack-ls
@@ -10,6 +10,16 @@ HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
 PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
 export PATH HUB_HOME HUB_EXTENSION
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 CURRENT=""
 if test -f ".env"; then
   CURRENT=$(basename "$(readlink .env)" .env)
@@ -44,7 +54,7 @@ print_stacks() {
       fi
       hubstate="$(dotenv -f "$f" get HUB_STATE)"
       if test -n "$hubstate"; then
-        resp="$(hub explain "$hubstate" --json | jq -cMr '{timestamp: .timestamp|split(".")|first, status: .status}')"
+        resp="$($hubctl explain "$hubstate" --json | jq -cMr '{timestamp: .timestamp|split(".")|first, status: .status}')"
         status=$(echo "$resp" | jq -cMr '.status')
         ts=$(echo "$resp" | jq -cMr '.timestamp')
       fi
diff --git a/profiles/toolbox/undeploy b/profiles/toolbox/undeploy
--- a/profiles/toolbox/undeploy
+++ b/profiles/toolbox/undeploy
@@ -5,5 +5,26 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
-echo "if test -e .env; then set -a; . .env; fi; exec hub undeploy $*" >.hub-toolbox
-exec hub toolbox bash .hub-toolbox
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
+cat << EOF >.hub-toolbox
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "\$hubctl"; then
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+
+if test -e .env; then 
+    set -a; 
+    . .env; 
+fi; 
+exec \$hubctl undeploy $*
+EOF
+exec $hubctl toolbox bash .hub-toolbox
