Renaming hub to hubctl epam/hubctl#22

diff --git a/azure/configure b/azure/configure
--- a/azure/configure
+++ b/azure/configure
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 # Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
@@ -14,7 +14,7 @@ usage() {
 Azure parameters:
   --azure-region                Azure Region (defaults to value from: AZURE_REGION, AZURE_DEFAULTS_LOCATION)
   --azure-resource-group        Azure Resource Group (defaults to value from: AZURE_RESOURCE_GROUP_NAME, AZURE_DEFAULTS_GROUP)
-  --azure-subscription          Azure Subscription (defaults to value from: AZURE_SUBSCRIPTION_ID)
+  --azure-subscription          Azure Subscription (defaults to value from: AZURE_SUBSCRIPTION_ID, ARM_SUBSCRIPTION_ID)
   --dry-run                     Do not deploy cloud resources, show what will happen
   --domain-name                 Custom DNS domain name under existing base domain
   --base-domain-resource-group  Resource Group for base domain (in case base domain
@@ -27,13 +27,13 @@ Bubble DNS parameters:
   --dns-update  Request to update DNS registration
 
   New DNS record request:
-    --parent-domain       Parent domain for stack (defaults to: bubble.superhub.io)
+    --parent-domain       Parent domain for stack (defaults to: epam.devops.delivery)
 
   Request to update DNS record:
     --domain-name         Previously issued DNS name
     --bubbles-secret-key  Secret key passed during domain name creation
 
-  Use: hub configure -r azure --dns-update
+  Use: hubctl configure -r azure --dns-update
 
 EOF
 }
@@ -92,70 +92,213 @@ if test "$VERBOSE" = "true"; then
 fi
 
 if test -z "$DOT_ENV"; then
-  echo "Error: please run with option: $0 --output FILE"
+  color error "Error: please run with option: $0 --output FILE"
   exit 2
 fi
-
-source $(dirname "$0")/../bubble-dns/include
-
+jq="jq -cMr"
 dotenv="dotenv -f $DOT_ENV"
+
+getParamFromState() {
+  # shellcheck disable=SC2016
+  hubctl explain "$1" --json | $jq --arg "param" "$2" '.stackParameters[$param] | select(.)'
+}
+
+getParamValueByEnvVar() {
+  param="$(params envvar "$2" | jq -cMr '.name')"
+  if test -n "$param"; then
+    getParamFromState "$1" "$param"
+  fi
+}
+
+param_name() {
+  local result
+  result="$(params env "$1" | jq -r '.name | select(.)')"
+  if test -z "$result" -a -n "$2"; then
+    result="$(params json "$2" | jq -r '.name | select(.)')"
+  fi
+  echo "$result"
+}
+
+stackname_param="$(param_name HUB_STACK_NAME dns.name)"
+dnsdomain_param="$(param_name HUB_DOMAIN_NAME dns.domain)"
+# hubfile does not have "dns.domain"
+if test -z "$dnsdomain_param"; then
+  # in this case we don't want bubble dns to autogenerate
+  DNS_MANAGER="user"
+  if test -n "$stackname_param"; then
+    # taking dns.domain from stack name
+    HUB_STACK_NAME="$(params value "$stackname_param" -d "$DOT_ENV" -d "$HUB_WORKDIR/.env")"
+    if test -n "$HUB_STACK_NAME"; then
+      echo -n "Using stack name: "
+      color b "$HUB_STACK_NAME"
+      HUB_DOMAIN_NAME="$HUB_STACK_NAME"
+    fi
+  fi
+fi
+
+# shellcheck disable=SC1091
+source "$(dirname "$0")/../bubble-dns/include"
+if test "DNS_MANAGER" = "bubbles"; then
+  if test -n "$HUB_DOMAIN_SECRET"; then
+    DNS_ACTION="update"
+  fi
+fi
 
 if test "$DNS_ACTION" = "update"; then
   updateBubbleDNS "$HUB_DOMAIN_NAME" "$HUB_DOMAIN_SECRET"
   exit $?
 fi
-
 if test -z "$HUB_DOMAIN_NAME"; then
   configureBubbleDNS
 elif test -z "$HUB_DOMAIN_SECRET"; then
   DNS_MANAGER=user
-  echo "* Using domain name provided by user: $HUB_DOMAIN_NAME"
+  echo -n "* Using domain name provided by user: "; color b "$HUB_DOMAIN_NAME"
 fi
 
-# https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration
-# AZURE_DEFAULTS_* automatically recognized up by `az`
-eval $(az configure --list-defaults | jq -r '.[] | "AZURE_CONFIG_DEFAULTS_" + (.name | ascii_upcase) + "=" + .value')
+if test -n "$AZURE_SUBSCRIPTION_ID"; then
+  echo "* Using Azure subscription from AZURE_SUBSCRIPTION_ID"
+  AZ_OPTS="$AZ_OPTS --subscription $AZURE_SUBSCRIPTION_ID"
+else
+  AZURE_SUBSCRIPTION_ID="$(params value 'azure.azureSubscriptionId')"
+  if test -z "$AZURE_SUBSCRIPTION_ID"; then
+    subscription_param="$(param_name AZURE_SUBSCRIPTION_ID)"
+    if test -n "$subscription_param"; then
+      AZURE_SUBSCRIPTION_ID="$(params value "$subscription_param")"
+    fi
+    if test -z "$AZURE_SUBSCRIPTION_ID"; then
+      subscription_param="$(param_name ARM_SUBSCRIPTION_ID)"
+      if test -n "$subscription_param"; then
+        AZURE_SUBSCRIPTION_ID="$(params value "$subscription_param")"
+      fi
+    fi
+  fi
+  if test -n "$AZURE_SUBSCRIPTION_ID"; then
+    echo "* Using Azure subscription from hubfile"
+    AZ_OPTS="$AZ_OPTS --subscription $AZURE_SUBSCRIPTION_ID"
+  fi
+fi
 
-location=${AZURE_REGION:-${AZURE_DEFAULTS_LOCATION:-$AZURE_CONFIG_DEFAULTS_LOCATION}}
-if test -z "$location"; then
-  echo "Error: please run with option: $0 --azure-region REGION"
+if test -z "$AZURE_SUBSCRIPTION_ID" -a -n "$ARM_SUBSCRIPTION_ID"; then
+  echo "* Using Azure subscription from ARM_SUBSCRIPTION_ID"
+  AZURE_SUBSCRIPTION_ID="$ARM_SUBSCRIPTION_ID"
+  AZ_OPTS="$AZ_OPTS --subscription $ARM_SUBSCRIPTION_ID"
+else
+  AZURE_SUBSCRIPTION_ID="$(az account list --query '[?isDefault].id' -o tsv)"
+  if test -n "$AZURE_SUBSCRIPTION_ID"; then
+    echo "* Using Azure default subscription from azure config"
+  else
+    AZURE_SUBSCRIPTION_ID=$(az account show -o json | jq -r .id)
+    if test -n "$AZURE_SUBSCRIPTION_ID"; then
+      echo "* Using Azure subscription from account"
+    fi
+  fi
+fi
+if test -z "$AZURE_SUBSCRIPTION_ID"; then
+  color error "Error: please run with option: $0 --azure-subscription SUBSCRIPTION_ID"
   exit 2
 fi
-echo "* Using Azure location: $location"
-AZ_LOCATION_OPTS=
-if test -n "$AZURE_REGION"; then
-  AZ_LOCATION_OPTS="--location $AZURE_REGION"
-fi
 
-resource_group=${AZURE_RESOURCE_GROUP_NAME:-${AZURE_DEFAULTS_GROUP:-$AZURE_CONFIG_DEFAULTS_GROUP}}
+echo -n "  Setting Azure subscription: "; color b "$AZURE_SUBSCRIPTION_ID"
+resource_group="$(params value 'azure.resourceGroup')"
 if test -z "$resource_group"; then
-  echo "Error: please run with option: $0 --azure-resource-group RESOURCE_GROUP"
+  resource_group_param="$(param_name AZURE_RESOURCE_GROUP_NAME)"
+  if test -n "$resource_group_param"; then
+    resource_group="$(params value "$resource_group_param")"
+  fi
+fi
+
+if test -n "$resource_group"; then
+  echo "* Using Azure resource group from hubfile"
+else
+  resource_group=${AZURE_RESOURCE_GROUP_NAME:-${AZURE_DEFAULTS_GROUP:-$AZURE_CONFIG_DEFAULTS_GROUP}}
+  if test -n "$resource_group"; then
+    echo "* Using Azure resource group from environment variables"
+  else
+    set +e
+    resource_group=$(az config get defaults.group --query 'value' -o tsv 2>/dev/null)
+    set -e
+    if test -n "$resource_group"; then
+      echo "* Using Azure resource group from azure config defaults.group"
+    fi
+  fi
+fi
+
+if test -z "$resource_group"; then
+  color error "Error: please run with option: $0 --azure-resource-group RESOURCE_GROUP"
   exit 2
 fi
-echo "* Using Azure resource group: $resource_group"
+
+echo -n "  Setting Azure resource group: "; color b "$resource_group"
+AZURE_RESOURCE_GROUP_NAME="$resource_group"
 if test -n "$AZURE_RESOURCE_GROUP_NAME"; then
   AZ_OPTS="$AZ_OPTS --resource-group $AZURE_RESOURCE_GROUP_NAME"
 fi
 
-if test -n "$AZURE_SUBSCRIPTION_ID"; then
-  AZ_OPTS="$AZ_OPTS --subscription $AZURE_SUBSCRIPTION_ID"
-else
-  AZURE_SUBSCRIPTION_ID=$(az account show -o json | jq -r .id)
-fi
-echo "* Using Azure subscription: $AZURE_SUBSCRIPTION_ID"
+
 export AZ_OPTS
+
+if test -z "$AZURE_REGION"; then
+  AZURE_REGION="$(params value 'azure.location')"
+  if test -z "$AZURE_REGION"; then
+    region_param="$(param_name AZURE_REGION)"
+    if test -n "$region_param"; then
+      AZURE_REGION="$(params value "$region_param")"
+    fi
+    region_param="$(param_name AZURE_LOCATION)"
+    if test -n "$region_param"; then
+      AZURE_REGION="$(params value "$region_param")"
+    fi
+  fi
+  if test -n "$AZURE_REGION"; then
+    echo "* Using Azure location from hubfile"
+    location="$AZURE_REGION"
+  fi
+fi
+
+if test -z "$AZURE_REGION"; then
+  # https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration
+  # AZURE_DEFAULTS_* automatically recognized up by `az`
+  eval $(az configure --list-defaults | jq -r '.[] | "AZURE_CONFIG_DEFAULTS_" + (.name | ascii_upcase) + "=" + .value')
+
+  location=${AZURE_REGION:-${AZURE_DEFAULTS_LOCATION:-$AZURE_CONFIG_DEFAULTS_LOCATION}}
+  if test -n "$location"; then
+    echo "* Using Azure location from environment variables"
+  else
+    location="$(az group show $AZ_OPTS -o tsv --query 'location')"
+    if test -n "$location"; then
+      echo "* Using Azure location from resource group $AZURE_RESOURCE_GROUP_NAME"
+    else
+      set +e
+      location=$(az config get defaults.location --query 'value' -o tsv 2>/dev/null)
+      set -e
+      if test -n "$location"; then
+        echo "* Using Azure location from azure config defaults.location"
+      fi
+    fi
+  fi
+fi
+if test -z "$location"; then
+  color error "Error: please run with option: $0 --azure-region REGION"
+  exit 2
+fi
+
+echo -n "  Setting Azure location: "; color b "$location"
+AZ_LOCATION_OPTS=""
+if test -n "$AZURE_REGION"; then
+  AZ_LOCATION_OPTS="--location $AZURE_REGION"
+fi
 
 # TODO state storage account per region?
 echo "Configuring Azure Storage Account"
 if test -z "$HUB_STATE_BUCKET"; then
-  HUB_STATE_BUCKET="superhub$(echo $AZURE_SUBSCRIPTION_ID | cut -d- -f1)"
+  HUB_STATE_BUCKET="hubctl$(echo $AZURE_SUBSCRIPTION_ID | cut -d- -f1)"
 fi
 if test -z "$HUB_STATE_CONTAINER"; then
-  HUB_STATE_CONTAINER=superhub
+  HUB_STATE_CONTAINER=hubctl
 fi
 
 echo -n "* Checking presence of storage account $resource_group/$HUB_STATE_BUCKET: "
-if az storage account show $AZ_OPTS -n $HUB_STATE_BUCKET -o none 2>/dev/null; then
+if az storage account show $AZ_OPTS -n "$HUB_STATE_BUCKET" -o none 2>/dev/null; then
   echo "exist"
 else
   if $DRY_RUN; then
@@ -167,11 +310,11 @@ else
     if test -n "$HUB_STATE_REGION"; then
       AZ_STORAGE_LOCATION_OPTS="--location $HUB_STATE_REGION"
     fi
-    az storage account create $AZ_OPTS $AZ_STORAGE_LOCATION_OPTS --sku Standard_ZRS --kind StorageV2 -n $HUB_STATE_BUCKET -o none
+    az storage account create $AZ_OPTS $AZ_STORAGE_LOCATION_OPTS --sku 'Standard_ZRS' --kind 'StorageV2' -n "$HUB_STATE_BUCKET" -o none
   fi
 fi
 echo -n "* Checking presence of storage account $resource_group/$HUB_STATE_BUCKET blob container $HUB_STATE_CONTAINER: "
-if az storage container show $AZ_OPTS --account-name $HUB_STATE_BUCKET -n $HUB_STATE_CONTAINER -o none 2>/dev/null; then
+if az storage container show $AZ_OPTS --account-name "$HUB_STATE_BUCKET" -n "$HUB_STATE_CONTAINER" -o 'none' 2>/dev/null; then
   echo "exist"
 else
   if $DRY_RUN; then
@@ -217,7 +360,7 @@ and creating a zone "$HUB_DOMAIN_NAME" or "$PARENT_DOMAIN".
 
 Then run again:
 
-$ hub configure -r azure --domain-name $HUB_DOMAIN_NAME
+$ hubctl configure -r azure --domain-name $HUB_DOMAIN_NAME
 
 Abort!
 EOF
@@ -247,13 +390,15 @@ else
 fi
 
 export HUB_CLOUD_PROVIDER=azure
-$dotenv set 'HUB_CLOUD_PROVIDER="azure"'
-test -z "$AZURE_REGION"              || $dotenv set "AZURE_REGION=\"$AZURE_REGION\""
-test -z "$AZURE_RESOURCE_GROUP_NAME" || $dotenv set "AZURE_RESOURCE_GROUP_NAME=\"$AZURE_RESOURCE_GROUP_NAME\""
-test -z "$AZURE_SUBSCRIPTION_ID"     || $dotenv set "AZURE_SUBSCRIPTION_ID=\"$AZURE_SUBSCRIPTION_ID\""
-test -z "$HUB_STATE_BUCKET"          || $dotenv set "HUB_STATE_BUCKET=\"$HUB_STATE_BUCKET\""
-test -z "$HUB_STATE_CONTAINER"       || $dotenv set "HUB_STATE_CONTAINER=\"$HUB_STATE_CONTAINER\""
-test -z "$HUB_STATE_REGION"          || $dotenv set "HUB_STATE_REGION=\"$HUB_STATE_REGION\""
+$dotenv set 'HUB_CLOUD_PROVIDER' 'azure'
+
+$dotenv contains 'AZURE_REGION'              || $dotenv set 'AZURE_REGION' "$AZURE_REGION"
+$dotenv contains 'AZURE_RESOURCE_GROUP_NAME' || $dotenv set 'AZURE_RESOURCE_GROUP_NAME' "$AZURE_RESOURCE_GROUP_NAME"
+$dotenv contains 'AZURE_SUBSCRIPTION_ID'     || $dotenv set 'AZURE_SUBSCRIPTION_ID' "$AZURE_SUBSCRIPTION_ID"
+$dotenv contains 'ARM_SUBSCRIPTION_ID'       || $dotenv set 'ARM_SUBSCRIPTION_ID' "$AZURE_SUBSCRIPTION_ID"
+$dotenv contains 'HUB_STATE_BUCKET'          || $dotenv set 'HUB_STATE_BUCKET' "$HUB_STATE_BUCKET"
+$dotenv contains 'HUB_STATE_CONTAINER'       || $dotenv set 'HUB_STATE_CONTAINER' "$HUB_STATE_CONTAINER"
+$dotenv contains 'HUB_STATE_REGION'          || $dotenv set 'HUB_STATE_REGION' "$HUB_STATE_REGION"
 
 if ! $DRY_RUN && test -n "$HUB_DOMAIN_SECRET"; then
   # TODO supply NS records as args
@@ -261,25 +406,25 @@ if ! $DRY_RUN && test -n "$HUB_DOMAIN_SECRET"; then
   cat <<EOF
 * DNS record has time to live: 72 hours
 
-# Hint! To refresh DNS: hub configure -r azure --dns-update
+# Hint! To refresh DNS: hubctl configure -r azure --dns-update
 
 EOF
 fi
 
 STACK=${STACK:-$(basename "$(pwd)")}
 if test -z "$HUB_STATE"; then
-  echo "* Setting hub state file location"
+  echo "* Setting hubctl state file location"
   HUB_STATE_FILE=".hub/$HUB_DOMAIN_NAME.state"
   if ! $PREFER_LOCAL_STATE; then
     HUB_STATE_FILE="$HUB_STATE_FILE,az://$HUB_STATE_BUCKET/$HUB_STATE_CONTAINER/$HUB_DOMAIN_NAME/hub/$STACK/hub.state"
   fi
-  $dotenv set "HUB_STATE=\"$HUB_STATE_FILE\""
+  $dotenv set 'HUB_STATE' "$HUB_STATE_FILE"
 fi
 if test -z "$HUB_ELABORATE"; then
-  echo "* Setting hub elaborate file location"
+  echo "* Setting hubctl elaborate file location"
   HUB_ELABORATE_FILE=".hub/$HUB_DOMAIN_NAME.elaborate"
   if ! $PREFER_LOCAL_STATE; then
     HUB_ELABORATE_FILE="$HUB_ELABORATE_FILE,az://$HUB_STATE_BUCKET/$HUB_STATE_CONTAINER/$HUB_DOMAIN_NAME/hub/$STACK/hub.elaborate"
   fi
-  $dotenv set "HUB_ELABORATE=\"$HUB_ELABORATE_FILE\""
+  $dotenv set 'HUB_ELABORATE' "$HUB_ELABORATE_FILE"
 fi
diff --git a/hub-show b/hub-show
--- a/hub-show
+++ b/hub-show
@@ -13,6 +13,17 @@ HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
 PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
 export PATH
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 usage()
 {
 cat << EOF
@@ -33,14 +44,12 @@ EOF
 
 FORMAT="${FORMAT:-yaml}"
 JQ_ARGS="${JQ_ARGS:- -Sr}"
-JQ_QUERY="${JQ_QUERY:-.}"
 eval "$(dotenv -f $HUB_WORKDIR/.env export)"
 
 if ! test -t 0; then
     HUB_DOMAIN_NAME=$(< /dev/stdin xargs | cut -d " " -f1 | tr -d '"')
 fi
 
-JQ_QUERY=""
 while [ "$1" != "" ]; do
     case $1 in
         -s | --stack )      shift
@@ -61,13 +70,14 @@ while [ "$1" != "" ]; do
                             ;;
         -q | -jq |--query ) shift
                             TRANSFORM=1
-                            JQ_QUERY="$1"
+                            JQ_ARGS="$JQ_ARGS $1"
                             ;;
         -v | --verbose )    set -x
                             ;;
         - )                 HUB_DOMAIN_NAME=$(< /dev/stdin xargs | cut -d " " -f1)
                             ;;
         -- )                shift
+                            # pass all the rest to jq
                             JQ_ARGS="$JQ_ARGS $*"
                             break
                             ;;
@@ -100,7 +110,7 @@ if test -z "$HUB_STATE"; then
 fi
 
 if test -z "$HUB_TOKEN"; then
-  RESP=$(hub explain "$HUB_STATE" --json || echo "") # this will spill into stderr on error
+  RESP=$($hubctl explain "$HUB_STATE" --json || echo "") # this will spill into stderr on error
   if test -z "$RESP"; then
     if test -z "$HUB_FILES"; then
       HUB_FILES="$(dotenv get HUB_FILES)"
@@ -136,7 +146,7 @@ if test -z "$HUB_TOKEN"; then
     fi
   fi
 else
-  RESP=$(hub api instance get -j \
+  RESP=$($hubctl api instance get -j \
       | jq -S '. | if type=="array" then . else [.] end' \
       | jq -cMr '.[] | select(.domain=="'$HUB_DOMAIN_NAME'")')
 fi
@@ -256,10 +266,10 @@ fi
 if test "$FORMAT" = "yaml"; then
     # shellcheck disable=SC2090
     echo "$DOCBASE" "$DOCEXT" | jq -cMs 'reduce .[] as $item ({}; . * $item) ' \
-    | jq $JQ_ARGS "$JQ_QUERY | select(.)" \
+    | jq $JQ_ARGS \
     | yq e -P 'del(.. | select((tag == "!!map" and length == 0) or (tag == "!!seq" and length == 0) or (. == null)))' -
 else
     # shellcheck disable=SC2090
     echo "$DOCBASE" "$DOCEXT" | jq -cMs 'reduce .[] as $item ({}; . * $item) ' \
-    | jq $JQ_ARGS "$JQ_QUERY | select(.)"
+    | jq $JQ_ARGS
 fi
diff --git a/hub-stack-elaborate b/hub-stack-elaborate
--- a/hub-stack-elaborate
+++ b/hub-stack-elaborate
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 # Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
@@ -19,7 +19,7 @@ Assemble hub.yaml.elaborate stack deployment manifest from hub.yaml,
 params.yaml-s, and hub-components.yaml-s
 
 Usage:
-$ hub stack elaborate
+$ hubctl stack elaborate
 
 Parameters:
     -V  --verbose          Verbose outputs for debug purpose
@@ -27,6 +27,17 @@ Parameters:
 
 EOF
 }
+
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
 
 if test ! -f .env; then
   echo "* Error: configuration '.env' has not been found"
@@ -60,12 +71,12 @@ echo "* Using domain name: $HUB_DOMAIN_NAME"
 
 if test -z "$HUB_FILES"; then
   cat << EOF
-Error: cannot find hub definition files (HUB_FILES)"
+Error: cannot find hubctl definition files (HUB_FILES)"
 
 Probably because stack has not been configured for deployment yet!
 
 Example:
-  $ hub configure -f hub.yaml
+  $ hubctl configure -f hub.yaml
 
 EOF
 
@@ -79,7 +90,7 @@ if test -z "$HUB_STATE"; then
 fi
 
 # if test -n "$HUB_STATE"; then
-#   echo "* Using hub state: $HUB_STATE"
+#   echo "* Using hubctl state: $HUB_STATE"
 #   HUB_OPTS="$HUB_OPTS -s $HUB_STATE"
 # fi
 
@@ -93,7 +104,7 @@ Proceeding with: elaborate
 * Result will be saved saved to: $HUB_ELABORATE
 * Running CLI command:
 
-  $ hub elaborate $HUB_FILES -o $HUB_ELABORATE $HUB_OPTS
+  $ hubctl elaborate $HUB_FILES -o $HUB_ELABORATE $HUB_OPTS
 
 EOF
 
@@ -118,7 +129,7 @@ done
 
 
 # shellcheck disable=SC2086
-hub elaborate $HUB_FILES -o "$HUB_ELABORATE" $HUB_OPTS
+$hubctl elaborate $HUB_FILES -o "$HUB_ELABORATE" $HUB_OPTS
 
 AFTER=$(yq -N e .extensions.${verb}.after.[] $HUB_FILES | sort | uniq)
 for i in $(echo "$AFTER" | xargs -n1); do
diff --git a/hub-stack-init b/hub-stack-init
--- a/hub-stack-init
+++ b/hub-stack-init
@@ -17,10 +17,21 @@ export PATH HUB_HOME HUB_EXTENSION
 HUB_WORKDIR="$(files abspath "$HUB_WORKDIR")"
 export HUB_WORKDIR
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 jq="jq -cMr "
 
 hub_state_cli_exist() {
-  hub state --help >/dev/null 2>&1
+  hubctl state --help >/dev/null 2>&1
 }
 
 real_files() {
@@ -39,7 +50,7 @@ toJson() {
 # shellcheck disable=SC2120
 usage() {
   cat << EOF
-Initializes a brand new stack from existing hub file
+Initializes a brand new stack from existing hubctl file
 
 Usage:
   $HUB_EXTENSION [flags] <state-ref>
@@ -52,7 +63,7 @@ Example:
   $HUB_EXTENSION <state-ref> -f <path-or-url-hub.yaml> --force
 
 State ref:
-  State can be referenced as a file, http, gs url or id (see "hub state ls")
+  State can be referenced as a file, http, gs url or id (see "hubctl state ls")
 
 EOF
 
@@ -246,7 +257,7 @@ componentSourceRef() {
 }
 
 getParamFromState() {
-  hub explain "$1" --json | $jq --arg "param" "$2" '.stackParameters[$param] | select(.)'
+  hubctl explain "$1" --json | $jq --arg "param" "$2" '.stackParameters[$param] | select(.)'
 }
 
 getParamValueByEnvVar() {
@@ -300,7 +311,7 @@ done
 if test -n "$SOURCE_HUB_STATE"; then
   # backward compatibility for users who have not installed new hub-state extension
   if hub_state_cli_exist; then
-    _state="$(hub state show "$SOURCE_HUB_STATE" -o json | $jq '.stateLocation.uri | select(.)')"
+    _state="$($hubctl state show "$SOURCE_HUB_STATE" -o json | $jq '.stateLocation.uri | select(.)')"
     if test -n "$_state"; then
       echo "Found state file: $_state"
       SOURCE_HUB_STATE="$_state"
@@ -309,7 +320,7 @@ if test -n "$SOURCE_HUB_STATE"; then
 fi
 
 if test -n "$SOURCE_HUB_STATE"; then
-  echo "Checking hub state"
+  echo "Checking hubctl state"
   for state in $(echo "$SOURCE_HUB_STATE" |tr ',' ' '); do
     temp="$(temp_file)"
     if test -f "$state"; then
@@ -328,10 +339,10 @@ if test -n "$SOURCE_HUB_STATE"; then
       gsutil -q cp "$state" "$temp"
       echo "done"
 
-      state_name="$(hub explain "$temp" --json | $jq '.meta.name | select(.)')"
-      state_status="$(hub explain "$temp" --json | $jq '.status | select(.)')"
+      state_name="$($hubctl explain "$temp" --json | $jq '.meta.name | select(.)')"
+      state_status="$($hubctl explain "$temp" --json | $jq '.status | select(.)')"
       echo "  Downloaded state: $state_name (status: $state_status)"
-      state_msg="$(hub explain "$temp" --json | $jq '.message | select(.)')"
+      state_msg="$($hubctl explain "$temp" --json | $jq '.message | select(.)')"
       if test -n "$state_msg"; then
         echo "  Message: $state_msg"
       fi
@@ -366,7 +377,7 @@ if test -n "$SOURCE_HUB_STATE"; then
   done
 elif test -z "$(params -f "$HUB_FILES" envvar HUB_DOMAIN_NAME)" \
        -a -z "$(params -f "$HUB_FILES" envvar HUB_STACK_NAME)"; then
-  echo "Checking hub files for domain name parameters"
+  echo "Checking hubctl files for domain name parameters"
   HUB_DOMAIN_NAME="$(params -f "$HUB_FILES" value "dns.domain")"
   HUB_STACK_NAME="$(params -f "$HUB_FILES" value "dns.name")"
   if test -z "$HUB_DOMAIN_NAME" -a -n "$HUB_STACK_NAME"; then
@@ -525,10 +536,10 @@ if test "$HUB_AUTOCONFIGURE" = "0"; then
 Next step: apply deployment configuration
 
 Run:
-  hub stack configure
+  hubctl stack configure
 
 For more details:
-  hub stack configure --help
+  hubctl stack configure --help
 
 EOF
 else
@@ -536,13 +547,13 @@ else
 Next step: start deploy or undeploy operations
 
 Run:
-  hub stack deploy
+  hubctl stack deploy
 or:
-  hub stack undeploy
+  hubctl stack undeploy
 
 For more details:
-  hub stack deploy --help
-  hub stack undeploy --help
+  hubctl stack deploy --help
+  hubctl stack undeploy --help
 
 EOF
 fi
diff --git a/kubernetes/after-deploy b/kubernetes/after-deploy
--- a/kubernetes/after-deploy
+++ b/kubernetes/after-deploy
@@ -11,6 +11,16 @@ dotenv="dotenv -f $HUB_WORKDIR/.env"
 
 export PATH
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 usage() {
   echo "Check Kubernetes cluster is reachable"
 }
@@ -93,7 +103,7 @@ cat << EOF
 * Trying kubeconfig from state: $STATEFILE
 * Running CLI command:
 
-  $ hub kubeconfig -k $HUB_STATE -c $HUB_DOMAIN_NAME
+  $ hubctl kubeconfig -k $HUB_STATE -c $HUB_DOMAIN_NAME
 
 EOF
 {
@@ -102,7 +112,7 @@ EOF
   export KUBECONFIG="$_temp"
   # shellcheck disable=SC2064
   trap "rm -f $_temp" EXIT
-  if hub kubeconfig -k "$HUB_STATE" -c "$HUB_DOMAIN_NAME"; then
+  if $hubctl kubeconfig -k "$HUB_STATE" -c "$HUB_DOMAIN_NAME"; then
     if checkClusterAndSave "$KUBECONFIG" ; then
       exit 0
     fi
diff --git a/profiles/local/undeploy b/profiles/local/undeploy
--- a/profiles/local/undeploy
+++ b/profiles/local/undeploy
@@ -5,13 +5,17 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
-# Simple wrapper script around hub undeploy
+# Simple wrapper script around hubctl undeploy
 
-HUB=$(which hub)
-if test -z "$HUB"; then
-  echo "Error: hub cli cannot be found"
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
   exit 1
 fi
 
 # shellcheck disable=SC2068
-$HUB undeploy $@
+$hubctl undeploy $@
diff --git a/profiles/pod/impl b/profiles/pod/impl
--- a/profiles/pod/impl
+++ b/profiles/pod/impl
@@ -20,6 +20,16 @@ Parameters:
 EOF
 }
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 if test -f ".env"; then
   eval "$(dotenv -f $HUB_WORKDIR/.env export -f ".env" )"
 fi
@@ -63,7 +73,7 @@ finalize() {
   # Will be better but harder to implement
   for f in ${STATE_FILE//,/ }; do
     if ! echo "$f" | grep -F :// >/dev/null; then
-      echo -n "* Downloading hub state to $(basename "$f"): "
+      echo -n "* Downloading hubctl state to $(basename "$f"): "
       $kubectl cp "toolbox-$ID:$f" "$f" >/dev/null 2>&1
       echo "Done"
     fi
@@ -198,6 +208,6 @@ if test -t 0; then
 fi
 echo -n "* Executing: "
 # shellcheck disable=SC2086
-echo $kubectl exec -i$maybe_tty "toolbox-$ID" -- gosu "$USER" tini -s -- $hub $HUB_ARGS
+echo $kubectl exec -i$maybe_tty "toolbox-$ID" -- gosu "$USER" tini -s -- $hubctl $HUB_ARGS
 # shellcheck disable=SC2086
-$kubectl exec -i$maybe_tty "toolbox-$ID" -- gosu "$USER" tini -s -- $hub $HUB_ARGS
+$kubectl exec -i$maybe_tty "toolbox-$ID" -- gosu "$USER" tini -s -- $hubctl $HUB_ARGS
