DNS update should not generate new domain name #63

diff --git a/azure/configure b/azure/configure
--- a/azure/configure
+++ b/azure/configure
@@ -152,26 +152,19 @@ EOF
   fi
 fi
 
-
-# shellcheck disable=SC1091
-source "$(dirname "$0")/../bubble-dns/include"
-if test "DNS_MANAGER" = "bubbles"; then
-  if test -n "$HUB_DOMAIN_SECRET"; then
-    DNS_ACTION="update"
-  fi
-fi
-
-if test "$DNS_ACTION" = "update"; then
-  updateBubbleDNS "$HUB_DOMAIN_NAME" "$HUB_DOMAIN_SECRET"
-  exit $?
+if test -z "$HUB_DOMAIN_NAME"; then
+  color error "Error: cannot find HUB_DOMAIN_NAME. This looks like a bug. Please report it."
+  exit 1
 fi
 
 if dotenv contains HUB_DOMAIN_SECRET; then
   DNS_MANAGER=bubbles
-  configureBubbleDNS
+  echo -n "* Using domain name provided by bubbles dns: ";
+  color b "$HUB_DOMAIN_NAME"
 else
   DNS_MANAGER=user
-  echo -n "* Using domain name provided by user: "; color b "$HUB_DOMAIN_NAME"
+  echo -n "* Using domain name provided by user: ";
+  color b "$HUB_DOMAIN_NAME"
 fi
 
 if test -n "$AZURE_SUBSCRIPTION_ID"; then
@@ -453,15 +446,23 @@ $dotenv contains 'HUB_STATE_CONTAINER'       || $dotenv set 'HUB_STATE_CONTAINER
 $dotenv contains 'HUB_STATE_REGION'          || $dotenv set 'HUB_STATE_REGION' "$HUB_STATE_REGION"
 $dotenv contains 'HUB_TOOLBOX_IMAGE'         || $dotenv set 'HUB_TOOLBOX_IMAGE' 'ghcr.io/epam/hub-toolbox:azure'
 
-if ! $DRY_RUN && test -n "$HUB_DOMAIN_SECRET" -a -n "$has_dnsdomain_param"; then
-  # TODO supply NS records as args
-  updateBubbleDNS "$HUB_DOMAIN_NAME" "$HUB_DOMAIN_SECRET"
-  cat <<EOF | color green
-  DNS record has time to live: 72 hours
+if test "$DNS_MANAGER" = "bubbles"; then
+  echo "* Sending dns propagation request to bubbles with domain zone: $HUB_DOMAIN_NAME"
+  bubbles_update="$(files -e find-in-path bubble-dns/update)"
+  ns_script="$(files -e find-in-path files find-in-path azure/dns/nameservers)"
+  ns_opts="--domain-name $HUB_DOMAIN_NAME --bubbles-secret-key $HUB_DOMAIN_SECRET"
+  for ns in $($ns_script --domain-name "$HUB_DOMAIN_NAME"); do
+    echo "  - $ns"
+    ns_opts="$ns_opts -ns $ns"
+  done
+  $bubbles_update $ns_opts
+# AK: remove this comment as curretnly misleading until we will resolve back 72 hours
+#   cat <<EOF | color green
+#   DNS record has time to live: 72 hours
 
-  Hint! To refresh DNS: hubctl configure -r azure --dns-update
+#   Hint! To refresh DNS: hubctl configure -r azure --dns-update
 
-EOF
+# EOF
 fi
 
 STACK=${STACK:-$(basename "$(pwd)")}
@@ -469,7 +470,7 @@ if test -z "$HUB_STATE"; then
   echo "* Setting hubctl state file location"
   HUB_STATE_FILE=".hub/$HUB_DOMAIN_NAME.state"
   if ! $PREFER_LOCAL_STATE; then
-    HUB_STATE_FILE="$HUB_STATE_FILE,az://$HUB_STATE_BUCKET/$HUB_STATE_CONTAINER/$HUB_DOMAIN_NAME/hub/$STACK/hub.state"
+    HUB_STATE_FILE="$HUB_STATE_FILE,az://$HUB_STATE_BUCKET/$HUB_STATE_CONTAINER/$HUB_DOMAIN_NAME/hubctl/$STACK/hub.state"
   fi
   $dotenv set 'HUB_STATE' "$HUB_STATE_FILE"
 fi
@@ -477,7 +478,7 @@ if test -z "$HUB_ELABORATE"; then
   echo "* Setting hubctl elaborate file location"
   HUB_ELABORATE_FILE=".hub/$HUB_DOMAIN_NAME.elaborate"
   if ! $PREFER_LOCAL_STATE; then
-    HUB_ELABORATE_FILE="$HUB_ELABORATE_FILE,az://$HUB_STATE_BUCKET/$HUB_STATE_CONTAINER/$HUB_DOMAIN_NAME/hub/$STACK/hub.elaborate"
+    HUB_ELABORATE_FILE="$HUB_ELABORATE_FILE,az://$HUB_STATE_BUCKET/$HUB_STATE_CONTAINER/$HUB_DOMAIN_NAME/hubctl/$STACK/hub.elaborate"
   fi
   $dotenv set 'HUB_ELABORATE' "$HUB_ELABORATE_FILE"
 fi
