Restructuring for extensions documentation

diff --git a/hub-configure b/hub-configure
--- a/hub-configure
+++ b/hub-configure
@@ -15,16 +15,14 @@ The result of configuration is saved under ".hub/env/" with a symlink ".env" poi
 to the current configuration.
 
 Usage:
-  hub configure <parameters>
+  $HUB_EXTENSION [-r requirement]
 
 Common parameters:
-  -r  --requirement       Configure one requirement (can be repeated multiple times)
-  -i  --init-dotenv FILE  Start with initial values from the .env FILE
-  -s  --silent            Suppress console outputs in favor of result codes
   -V  --verbose           Verbose outputs for debug purposes
   -h  --help              Print this message
 
-Use: hub configure -r aws -r kubernetes   # configure specified requirements only
+Use: hub configure
+     hub configure -r env # to reconfigure only environment variables
 
 Usage for stack requirements: [$(echo "$1" | xargs)]
 
@@ -68,32 +66,32 @@ while [ "$1" != "" ]; do
     -f | --file )
       shift
       HUB_FILES=$(echo "$HUB_FILES $1" | xargs)
+      continue
       ;;
-    # -C | --workdir )
-    #   shift
-    #   WORKDIR=$1
-    #   ;;
     --profile )
       shift
       HUB_DEPLOY_PROFILE="$1"
+      continue
       ;;
     -r | --requirement )
       shift
       REQS=$(echo "$REQS $1" | xargs)
       ;;
-    -i | --init-dotenv )
-      shift
-      INIT_DOTENV="$1"
-      ;;
+    # -i | --init-dotenv )
+    #   shift
+    #   INIT_DOTENV="$1"
+    #   ;;
     -S | --silent )
       SILENT=true
       ;;
     -V | --verbose )
       VERBOSE=true
+      continue
       ;;
     -h | --help )
       HELP=true
       ARGS="--help"
+      continue
       ;;
   esac
   shift
@@ -103,10 +101,10 @@ if $VERBOSE; then
   set -x
 fi
 
-if test -n "$INIT_DOTENV" -a ! -f "$INIT_DOTENV"; then
-  echo "Error: init dotenv $INIT_DOTENV file not found"
-  exit 1
-fi
+# if test -n "$INIT_DOTENV" -a ! -f "$INIT_DOTENV"; then
+#   echo "Error: init dotenv $INIT_DOTENV file not found"
+#   exit 1
+# fi
 
 TEMP_FILES=""
 temp_file(){
@@ -114,6 +112,24 @@ temp_file(){
   temp=$(mktemp) || exit 1
   TEMP_FILES="$TEMP_FILES $temp"
   echo $temp
+}
+
+find_in_path() {
+  local _file _path rv
+  _file="$(echo "$1" | sed -e 's/^\///')"
+  ( IFS=:
+    for _path in $PATH; do
+      if test -x "$_path/$_file"; then
+        rv="$_path/$_file"
+        echo "$rv"
+        break;
+      fi
+    done
+    if test -z "$rv"; then
+      >&2 echo "Error: command not found: $1"
+      exit 44
+    fi
+  )
 }
 
 download_file() {
@@ -314,11 +330,11 @@ trap 'finalize $?' EXIT
 
 MERGE_FILES=""
 
-if test -n "$INIT_DOTENV"; then
-  echo "Using $INIT_DOTENV as initial configuration"
-  eval $(dotenv export -f "$INIT_DOTENV")
-  MERGE_FILES="$MERGE_FILES -f $INIT_DOTENV"
-fi
+# if test -n "$INIT_DOTENV"; then
+#   echo "Using $INIT_DOTENV as initial configuration"
+#   eval $(dotenv export -f "$INIT_DOTENV")
+#   MERGE_FILES="$MERGE_FILES -f $INIT_DOTENV"
+# fi
 
 if test -f "$HUB_WORKDIR/.env"; then
   echo "Configuration .env file: exist"
@@ -336,14 +352,12 @@ fi
 echo "* Deployment profile: $HUB_DEPLOY_PROFILE"
 
 for req in $(echo "$REQS" | xargs -n1); do
-  if test -f "$HUB_WORKDIR/.hub/$req/configure"; then
-    configure="$HUB_WORKDIR/.hub/$req/configure"
-  elif test -f "$HUB_HOME/$req/configure"; then
-    configure="$HUB_HOME/$req/configure"
-  else
-    echo "* Cannot find configure script for \"$req\": skipping"
+  configure=$(find_in_path "$req/init")
+  if test -z "$configure"; then
+    color -c 3 -b "* Warning: cannot find configure script for \"$req\""
     continue
   fi
+
   DOT_ENV=$(temp_file)
   export DOT_ENV
   if ! $configure --output "$DOT_ENV" $ARGS; then
