Removed SILENT directive as obsolete. Added proper .env file sourcing

diff --git a/hub-stack-deploy b/hub-stack-deploy
--- a/hub-stack-deploy
+++ b/hub-stack-deploy
@@ -29,37 +29,15 @@ EOF
 }
 
 FULL_STACK=true
-NOGUIDE=${NOGUIDE:-false}
-SILENT=${SILENT:-false}
-CLOUD_CHECK=true
-WITH_PREREQS=false
-
 while test "$1" != ""; do
     case $1 in
-        -t | --with-toollbox )
-                            HUB_TOOLBOX="1"
-                            ;;
-        -p | --no-precheck )
-                            CLOUD_CHECK=false
-                            ;;
-        -P | --deploy-prereqs )
-                            WITH_PREREQS=true
-                            ;;
         -c | --component )  shift
                             HUB_DEPLOY_OPTS="$HUB_DEPLOY_OPTS -c $1"
                             FULL_STACK=false
-                            CLOUD_CHECK=false
                             ;;
         -o | --offset )     shift
                             HUB_DEPLOY_OPTS="$HUB_DEPLOY_OPTS -o $1"
                             FULL_STACK=false
-                            CLOUD_CHECK=false
-                            ;;
-        --skip-guide )      NOGUIDE=true
-                            ;;
-        -S | --silent )     SILENT=true
-                            NOGUIDE=true
-                            exit
                             ;;
         -V | --verbose )    set -x
                             ;;
@@ -81,8 +59,15 @@ $ hub configure --current-kubecontext
 EOF
   exit 1
 fi
-# shellcheck disable=SC1091
-source .env
+dotenv=$(dirname "$0")/env/dotenv
+set +a
+eval "$($dotenv export -f ".env" )"
+set -a
+
+if test -z "$HUB_DOMAIN_NAME"; then
+  echo "Error: HUB_DOMAIN_NAME has not been defined"
+  exit 2
+fi
 
 cat << EOF
 Starting deployment:
@@ -92,34 +77,6 @@ Starting deployment:
 EOF
 
 HUB=${HUB:-hub}
-
-if $CLOUD_CHECK; then
-  if ! $WITH_PREREQS; then
-    AWS_STATUS_ARGS="${AWS_STATUS_ARGS} --skip-guide"
-  fi
-
-  set +e
-  hub ext aws status $AWS_STATUS_ARGS
-  hub_aws_rv="$?"
-  set -e
-fi
-
-if test "$hub_aws_rv" = "2"; then
-  cat << EOF
-Error: Cannot find .env configuration. Please run:
-
-$ hub configure --current-kubeconfig
-
-EOF
-  exit "$hub_aws_rv"
-
-elif test "$hub_aws_rv" = "3"; then
-  if ! $WITH_PREREQS; then
-    exit $hub_aws_rv
-  fi
-  $HUB aws init --skip-guide
-fi
-
 HUB_ELABORATE_FILE="${HUB_ELABORATE_FILE:-".hub/$HUB_DOMAIN_NAME.elaborate"}"
 HUB_STATE_FILE="${HUB_STATE_FILE:-".hub/$HUB_DOMAIN_NAME.state"}"
 
@@ -133,7 +90,7 @@ fi
 
 # shellcheck disable=SC2086
 if $FULL_STACK || test ! -f "$HUB_ELABORATE_FILE"; then
-  $HUB stack elaborate --skip-guide
+  $HUB stack elaborate
 fi
 
 # shellcheck disable=SC2086
@@ -151,6 +108,7 @@ ns=kube-system
 cm=superhub
 explained=$($HUB explain --json -g $HUB_STATE_FILE | base64 | tr -d \\n)
 
+#TODO: this should go to the hub extension
 (
 if kubectl -n $ns get configmap $cm >/dev/null 2>&1; then
   kubectl -n $ns get configmap $cm -o json |
