`component terraform` continue if pre-* hooks export no vars

diff --git a/hub-component-terraform b/hub-component-terraform
--- a/hub-component-terraform
+++ b/hub-component-terraform
@@ -36,12 +36,13 @@ if test $verb == undeploy; then
     destroy=-destroy
 fi
 
-set +xe
+set -xe
 
 mkdir -p $TF_DATA_DIR
 
+# TODO fail on hooks error
 if test -x pre-init; then
-    tfvars=$(./pre-init | grep -E '^export ')
+    tfvars=$(./pre-init | grep -E '^export ' || exit 0)
     if test -n "$tfvars"; then eval "$tfvars"; fi
 fi
 
@@ -52,7 +53,7 @@ $terraform init -get=true $TF_CLI_ARGS -reconfigure -force-copy  \
     -backend-config="profile=$AWS_PROFILE"
 
 if test -x pre-$verb; then
-    tfvars=$(./pre-$verb | grep -E '^export ')
+    tfvars=$(./pre-$verb | grep -E '^export ' || exit 0)
     if test -n "$tfvars"; then eval "$tfvars"; fi
 fi
 
