Some extensions ignore HUB_WORKDIR variable #113

diff --git a/hub-component-download b/hub-component-download
--- a/hub-component-download
+++ b/hub-component-download
@@ -1,10 +1,15 @@
-#!/bin/bash -e
-# Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#!/bin/sh -e
+# Copyright (c) 2023 EPAM Systems, Inc.
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
-# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.
 
+HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
+HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
+HUB_EXTENSION="$(basename "$0" | sed 's/hub-/hubctl-/g' | sed 's/-/ /g')"
+PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
+export PATH
 
 usage() {
   cat << EOF
@@ -13,10 +18,10 @@ Helper tool that dowloads components specified in hub.yaml
 Use flags "-A" or "-C" to download all components or subset of them
 
 Usage:
-$ $(basename "$0") -A -F
+$ $HUB_EXTENSION -A -F
 To download all components and overwrite if they already exist
 
-$ $(basename "$0") -F -C minio,tiller
+$ $HUB_EXTENSION -F -C minio,tiller
 To download specified componenets and overwrite if they already exist
 
 
@@ -33,70 +38,75 @@ EOF
 
 # shellcheck disable=SC2086
 local_dir() {
-  local f res
-  for f in $HUB_FILES; do
-    res=$(
-      yq e -o=json "$f" | \
+  _local_dir_f=
+  _local_dir_res=
+  for _local_dir_f in $HUB_FILES; do
+    _local_dir_res=$(
+      yq e -o=json "$_local_dir_f" | \
       jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.dir'
     )
-    test -z "$res" || break
+    test -z "$_local_dir_res" || break
   done
-  echo "$res"
+  echo "$_local_dir_res"
 }
 
 # shellcheck disable=SC2086
 git_sub_dir() {
-    local f res
-    for f in $HUB_FILES; do
-      res=$(
-        yq e -o=json "$f" | \
-        jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.subDir|select(.)'
-      )
-      test -z "$res" || break
-    done
-    echo "$res"
+  _git_sub_dir_f=
+  _git_sub_dir_res=
+  for _git_sub_dir_f in $HUB_FILES; do
+    _git_sub_dir_res=$(
+      yq e -o=json "$_git_sub_dir_f" | \
+      jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.subDir|select(.)'
+    )
+    test -z "$_git_sub_dir_res" || break
+  done
+  echo "$_git_sub_dir_res"
 }
 
 # shellcheck disable=SC2086
 git_remote() {
-  local f res
-  for f in $HUB_FILES; do
-    res=$(
-      yq e -o=json "$f" | \
+  _git_remote_f=
+  _git_remote_res=
+  for _git_remote_f in $HUB_FILES; do
+    _git_remote_res=$(
+      yq e -o=json "$_git_remote_f" | \
       jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.remote|select(.)'
     )
-    test -z "$res" || break
+    test -z "$_git_remote_res" || break
   done
-  echo "$res"
+  echo "$_git_remote_res"
 }
 
 # shellcheck disable=SC2086
 git_cloned_dir() {
-  local f res
-  for f in $HUB_FILES; do
-    res=$(
-      yq e -o=json "$f" | \
+  _git_cloned_dir_f=
+  _git_cloned_dir_res=
+  for _git_cloned_dir_f in $HUB_FILES; do
+    _git_cloned_dir_res=$(
+      yq e -o=json "$_git_cloned_dir_f" | \
       jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.remote|select(.)|split("/")[-1] |split(".")[0]'
     )
-    test -z "$res" || break
+    test -z "$_git_cloned_dir_res" || break
   done
-  echo "$res"
+  echo "$_git_cloned_dir_res"
 }
 
 # shellcheck disable=SC2086
 git_ref() {
-  local f res
-  for f in $HUB_FILES; do
-    res=$(
-      yq e -o=json "$f" | \
+  _git_ref_f=
+  _git_ref_res=
+  for _git_ref_f in $HUB_FILES; do
+    _git_ref_res=$(
+      yq e -o=json "$_git_ref_f" | \
       jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.ref|select(.)'
     )
-    if test -n "$res"; then
-      echo "$res"
+    if test -n "$_git_ref_res"; then
+      echo "$_git_ref_res"
       break;
     fi
   done
-  if test -z "$res"; then
+  if test -z "$_git_ref_res"; then
     echo "main"
   fi
 }
@@ -106,15 +116,14 @@ if test -z "$*"; then
   exit 1
 fi
 
-if test -f ".env"; then
-  set +a
-  eval "$(dotenv export -f ".env" )"
-  set -a
+if test ! -f "$HUB_WORKDIR/.env"; then
+  color error "Error: cannot find .env file in $HUB_WORKDIR"
+  exit 1
 fi
+eval "$(dotenv export -f "$HUB_WORKDIR/.env")"
 
 CHECK=${CHECK:-true}
 COMPONENT_JSON_PATH=${COMPONENT_JSON_PATH:-.hub/component_rev.json}
-WORKDIR=${WORKDIR:-$(pwd)}
 while [ "$1" != "" ]; do
     case $1 in
     -f | --file)        shift
@@ -143,7 +152,7 @@ while [ "$1" != "" ]; do
 done
 
 if test -z "$HUB_FILES"; then
-  echo "Error: cannot find hubctl files. Please run this command with --file flag"
+  color error "Error: cannot find hubctl files. Please run this command with --file flag"
   exit 1
 fi
 
@@ -154,14 +163,15 @@ if test -z "$COMPONENTS"; then
     # GIT_URLS=$(yq e -o=json hub.yaml | jq -r '.components[].source.git.remote | select(length > 0)'  | sort | uniq)
   done
   if test -z "$COMPONENTS"; then
-    echo "Error: cannot find components in [$HUB_FILES]"
+    color error "Error: cannot find components in [$HUB_FILES]"
+    exit 2
   fi
 fi
 
 TEMP_DIR=$(mktemp -d)
 trap 'rm -rf $TEMP_DIR' EXIT
 for component in $COMPONENTS; do
-  echo -n "* Checking component $component: "
+  printf "* Checking component %s: " "$component"
   to_dir=$(local_dir "$component")
   if test -d "$to_dir"; then
     echo "already exists"
@@ -174,13 +184,13 @@ for component in $COMPONENTS; do
 
   temp="$TEMP_DIR/$(echo "$remote+$ref" | sed 's/[^0-9a-zA-Z-]*//g')"
   if test ! -d "$temp"; then
-    echo -n "  Cloning remote $remote ($ref): "
+    printf "  Cloning remote %s (%s): " "$remote" "$ref"
     git clone "$remote" "$temp" > /dev/null 2>&1
     git -C "$temp" checkout "$ref" > /dev/null 2>&1
     echo "done"
   fi
-  echo -n "  Store to $to_dir: "
-  mkdir -p "$(dirname $WORKDIR/$to_dir)"
-  cp -rf "$temp/$sub_dir" "$WORKDIR/$to_dir"
+  printf "  Store to %s: " "$to_dir"
+  mkdir -p "$(dirname "$HUB_WORKDIR/$to_dir")"
+  cp -rf "$temp/$sub_dir" "$HUB_WORKDIR/$to_dir"
   echo "Done"
 done
diff --git a/hub-stack-backup-create b/hub-stack-backup-create
--- a/hub-stack-backup-create
+++ b/hub-stack-backup-create
@@ -1,14 +1,12 @@
-#!/bin/bash -e
-# Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#!/bin/sh -e
+# Copyright (c) 2023 EPAM Systems, Inc.
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
-# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.
 
-# shellcheck disable=SC2086
 HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
 HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
-HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
 PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
 export PATH
 
@@ -22,6 +20,10 @@ if test -z "$hubctl"; then
   color error "hubctl not found in PATH. Please install hubctl first."
   exit 1
 fi
+
+is_url() {
+  echo "$1" | grep -e '^https\?://' >/dev/null 2>&1
+}
 
 usage() {
 cat << EOF
@@ -41,22 +43,19 @@ Parameters:
     -t --tag              Backup tags
     -c --component        Components to backup
     -V  --verbose         Verbose outputs for debug purpose
-    --tty                 Use TTY (terminal) mode for hubctl ${verb}
-    --no-tty              Do not use TTY (terminal) mode for hubctl ${verb}
-    --                    Separator to define "hubctl ${verb}" low level parameters (see: "hubctl ${verb} --help")
+    --tty                 Use TTY (terminal) mode for hubctl
+    --no-tty              Do not use TTY (terminal) mode for hubctl
+    --                    Separator to define "hubctl" low level parameters (see: "hubctl --help")
     -h  --help            Print this message
 
 EOF
 }
 
-
-if test ! -f .env; then
-  echo "* Error: configuration '.env' has not been found"
+if test ! -f "$HUB_WORKDIR/.env"; then
+  color error "Error: cannot find .env file in $HUB_WORKDIR"
   exit 1
 fi
-
-
-eval "$(dotenv -f $HUB_WORKDIR/.env "export")"
+eval "$(dotenv export -f "$HUB_WORKDIR/.env")"
 
 FULL_STACK=true
 HUB_OPTS=
@@ -109,20 +108,22 @@ elif test -n "$KUBECONFIG" -a -f "$KUBECONFIG"; then
 fi
 
 if test -z "$HUB_STATE"; then
-  HUB_STATE=".hub/$HUB_DOMAIN_NAME.state"
+  HUB_STATE="$HUB_WORKDIR/.hub/$HUB_DOMAIN_NAME.state"
 fi
+
 echo "* Using hubctl state:"
-for i in ${HUB_STATE//,/ }; do
+hub_state=$(echo "$HUB_STATE" | sed 's/,/ /g')
+for i in ${hub_state}; do
   echo "  - $i"
 done
 
 if test -z "$HUB_ELABORATE"; then
-  HUB_ELABORATE=".hub/$HUB_DOMAIN_NAME.elaborate"
+  HUB_ELABORATE="$HUB_WORKDIR/.hub/$HUB_DOMAIN_NAME.elaborate"
 fi
 echo "* Using hubctl elaborate:"
-for i in ${HUB_ELABORATE//,/ }; do
+for i in $(echo "$HUB_ELABORATE" | sed "s/,/ /g"); do
   echo "  - $i"
-  if ! grep :// <<<$i >/dev/null; then
+  if ! is_url "$i"; then
     HUB_ELABORATE_FILE=$i
   fi
 done
@@ -149,7 +150,7 @@ fi
 
 # export HUB_YAML HUB_FILES HUB_STATE HUB_ELABORATE
 if test -z "$HUB_BACKUP_DIR"; then
-  HUB_BACKUP_DIR=".hub/backups"
+  HUB_BACKUP_DIR="$HUB_WORKDIR/.hub/backups"
 fi
 
 hub_backup_dir="$HUB_BACKUP_DIR"
@@ -185,7 +186,7 @@ if test -n "$HUB_BACKUP_TAG"; then
     echo "  Unlinking $tag_path"
     unlink "$tag_path"
   fi
-  echo "  Reference to backup: $(basename $HUB_BACKUP_DIR)"
+  echo "  Reference to backup: $(basename "$HUB_BACKUP_DIR")"
   mkdir -p "$(dirname "$tag_path")"
   ln -s "$HUB_BACKUP_DIR" "$tag_path"
 fi
diff --git a/hub-stack-explain b/hub-stack-explain
--- a/hub-stack-explain
+++ b/hub-stack-explain
@@ -1,14 +1,14 @@
-#!/bin/bash -e
-# Copyright (c) 2022 EPAM Systems, Inc.
+#!/bin/sh -e
+# Copyright (c) 2023 EPAM Systems, Inc.
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
-# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.
 
 
 HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
 HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
-HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
+HUB_EXTENSION="$(basename "$0" | sed 's/hub-/hubctl-/g' | sed 's/-/ /g')"
 PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
 export PATH
 
@@ -53,10 +53,11 @@ while [ "$1" != "" ]; do
     shift
 done
 
-if test ! -f .env; then
-    echo "* Error: configuration '.env' not found"
-    exit 1
+if test ! -f "$HUB_WORKDIR/.env"; then
+  color error "Error: cannot find .env file in $HUB_WORKDIR"
+  exit 1
 fi
-eval "$(dotenv export -f "$HUB_WORKDIR/.env" )"
+eval "$(dotenv export -f "$HUB_WORKDIR/.env")"
 
+# shellcheck disable=SC2086
 $hubctl explain "$HUB_ELABORATE" "$HUB_STATE" $HUB_OPTS | less -R
diff --git a/kubernetes/after-deploy b/kubernetes/after-deploy
--- a/kubernetes/after-deploy
+++ b/kubernetes/after-deploy
@@ -1,15 +1,12 @@
-#!/bin/bash -e
+#!/bin/sh -e
 # Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
-# shellcheck disable=SC2068,SC2086,SC2155
-
+HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
 dotenv="dotenv -f $HUB_WORKDIR/.env"
-
-export PATH
 
 hubctl="$(which hubctl 2>/dev/null || true)"
 if test -z "$hubctl"; then
@@ -21,31 +18,27 @@ if test -z "$hubctl"; then
   exit 1
 fi
 
-usage() {
-  echo "Check Kubernetes cluster is reachable"
-}
-
 checkCluster() {
-  local KUBECONTEXT
+  _checkCluster_KUBECONTEXT=
   if test -n "$1";then
-    KUBECONFIG="$1"
+    _checkCluster_KUBECONTEXT="$1"
     export KUBECONFIG
-    echo "* Trying kubeconfig: $KUBECONFIG"
+    echo "* Trying kubeconfig: $_checkCluster_KUBECONTEXT"
   fi
-  KUBECONTEXT="$2"
+  _checkCluster_KUBECONTEXT="$2"
 
-  if test -z "$KUBECONTEXT"; then
-    KUBECONTEXT="$(kubectl config current-context)"
+  if test -z "$_checkCluster_KUBECONTEXT"; then
+    _checkCluster_KUBECONTEXT="$(kubectl config current-context)"
   fi
 
-  if test -z "$(kubectl config view -o json | jq ".contexts[] | select(.name==\"$KUBECONTEXT\").name")"; then
-    echo "* Context $KUBECONTEXT: not found"
+  if test -z "$(kubectl config view -o json | jq ".contexts[] | select(.name==\"$_checkCluster_KUBECONTEXT\").name")"; then
+    echo "* Context $_checkCluster_KUBECONTEXT: not found"
     return 1
   fi
-  echo "* Context $KUBECONTEXT: exist"
+  echo "* Context $_checkCluster_KUBECONTEXT: exist"
 
-  echo -n "* Checking connectivty to $KUBECONTEXT: "
-  if kubectl cluster-info --context="$KUBECONTEXT"> /dev/null; then
+  printf "* Checking connectivty to %s: " "$_checkCluster_KUBECONTEXT"
+  if kubectl cluster-info --context="$_checkCluster_KUBECONTEXT"> /dev/null; then
     echo "connected"
   else
     return $?
@@ -67,11 +60,11 @@ checkClusterAndSave() {
   fi
 }
 
-if test -f "$HUB_WORKDIR/.env"; then
-  set +a
-  eval "$($dotenv export)"
-  set -a
+if test ! -f "$HUB_WORKDIR/.env"; then
+  color error "Error: cannot find .env file in $HUB_WORKDIR"
+  exit 1
 fi
+eval "$($dotenv export)"
 
 echo "Finalizing kubernetes deployment"
 
@@ -86,7 +79,7 @@ else
   echo "* File .env does not provide HUB_KUBECONFIG"
 fi
 
-SAVETO="$(pwd)/.hub/env/$HUB_DOMAIN_NAME.kubeconfig"
+SAVETO="$HUB_WORKDIR/.hub/env/$HUB_DOMAIN_NAME.kubeconfig"
 if test -f "$SAVETO"; then
   if checkClusterAndSave "$SAVETO"; then
     exit 0
@@ -96,7 +89,7 @@ else
 fi
 
 if test -z "$HUB_STATE"; then
-  HUB_STATE=".hub/$HUB_DOMAIN_NAME.state"
+  HUB_STATE="$HUB_WORKDIR/.hub/$HUB_DOMAIN_NAME.state"
 fi
 
 cat << EOF
@@ -143,5 +136,5 @@ if test -d "/var/run/secrets/kubernetes.io/serviceaccount"; then
   fi
 fi
 
-echo "Error: unable to configure kubeconfig!"
+color error "Error: unable to configure kubeconfig!"
 exit 1
diff --git a/profiles/kubernetes/aws b/profiles/kubernetes/aws
--- a/profiles/kubernetes/aws
+++ b/profiles/kubernetes/aws
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 # Copyright (c) 2022 EPAM Systems, Inc.
-# 
+#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
@@ -26,9 +26,11 @@ if test -z "$POD"; then
   exit 1
 fi
 
-if test -f ".env"; then
-  eval "$(dotenv -f $HUB_WORKDIR/.env export)"
+if test ! -f "$HUB_WORKDIR/.env"; then
+  color error "Error: cannot find .env file in $HUB_WORKDIR"
+  exit 1
 fi
+eval "$(dotenv export -f "$HUB_WORKDIR/.env")"
 
 # these AWS_* vars are passed into pod by ./template as we may copy files to the non-default locations
 # or switch to the default locations instead
