Improvements of executers #111
- Changed script shebang to /bin/sh
- Pass to docker and kubernetes executors verbose flag
- Set verbosity in executors before other commands
- Bump license file headers

diff --git a/hub-stack-deploy b/hub-stack-deploy
--- a/hub-stack-deploy
+++ b/hub-stack-deploy
@@ -3,29 +3,10 @@
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
-# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.
 
 # shellcheck disable=SC2086
-
-HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
-HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
 HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
-HUB_MANUAL_ELABORATE="${HUB_MANUAL_ELABORATE:-"1"}"
-PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
-export PATH HUB_WORKDIR
-DOT_ENV="$(files abspath .env)"
-export DOT_ENV
-
-hubctl="$(which hubctl 2>/dev/null || true)"
-if test -z "$hubctl"; then
-  # backward compatibility
-  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
-  hubctl="$(which hub 2>/dev/null || true)"
-fi
-if test -z "$hubctl"; then
-  color error "hubctl not found in PATH. Please install hubctl first."
-  exit 1
-fi
 
 verb=deploy/undeploy
 
@@ -58,23 +39,9 @@ Parameters:
 EOF
 }
 
-is_url() {
-  echo "$1" | grep -e '^https\?://' >/dev/null 2>&1
-}
-
-maybe_verb=$(basename "$0" | cut -d- -f3)
-if test -z "$maybe_verb"; then
-  usage
-  exit 1
-fi
-verb="$maybe_verb"
-
-eval "$(dotenv -f $HUB_WORKDIR/.env "export")"
-
 FULL_STACK=true
-WORKDIR=$(pwd)
 HUB_OPTS=
-VERBOSE=false
+VERBOSE=
 
 while test "$1" != ""; do
     case $1 in
@@ -97,7 +64,7 @@ while test "$1" != ""; do
         --profile )         shift
                             export HUB_DEPLOY_PROFILE="$1"
                             ;;
-        -V | --verbose )    VERBOSE=true
+        -V | --verbose )    VERBOSE="true"
                             ;;
         -h | --help )       usage
                             exit
@@ -111,6 +78,43 @@ while test "$1" != ""; do
     esac
     shift
 done
+
+if test "$VERBOSE" = "true"; then
+  set -x
+  VERBOSE="--verbose"
+fi
+
+HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
+HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
+HUB_MANUAL_ELABORATE="${HUB_MANUAL_ELABORATE:-"1"}"
+PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
+export PATH HUB_WORKDIR
+DOT_ENV="$(files abspath .env)"
+export DOT_ENV
+
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
+is_url() {
+  echo "$1" | grep -e '^https\?://' >/dev/null 2>&1
+}
+
+maybe_verb=$(basename "$0" | cut -d- -f3)
+if test -z "$maybe_verb"; then
+  usage
+  exit 1
+fi
+verb="$maybe_verb"
+
+eval "$(dotenv -f $HUB_WORKDIR/.env "export")"
 
 finalize() {
   status="$($hubctl show -jq '.status.status')"
@@ -131,10 +135,6 @@ EOF
 }
 
 trap 'finalize $?' EXIT
-
-if test "$VERBOSE" = "true"; then
-  set -x
-fi
 
 if test ! -f .env; then
 color e << EOF
@@ -292,8 +292,7 @@ Proceeding with: ${verb}
 
 EOF
 
-# shellcheck disable=SC2086
-$lifecycle "$HUB_ELABORATE" -s "$HUB_STATE" $HUB_OPTS
+$lifecycle $VERBOSE "$HUB_ELABORATE" -s "$HUB_STATE" $HUB_OPTS
 echo
 
 AFTER=$(yq -N e .extensions.${verb}.after.[] $HUB_FILES | sort | uniq)
