Better handling for deployment parameters. before and after deploy hooks can be sourced from .hub directory

diff --git a/hub-configure b/hub-configure
--- a/hub-configure
+++ b/hub-configure
@@ -5,10 +5,10 @@ HUB_HOME=${HUB_HOME:-$(dirname "$0")}
 
 usage() {
   cat << EOF
-Reads configuration in hub.yaml and configures stack for deployment
+Reads configuration information in $HUB_FILES and configures stack for deployment
 
 Use: 
-  hub configure -f hub.yaml -f params.yaml <parameters>
+  hub configure -f hub.yaml <parameters>
 
 Common parameters:
   -f  --file              Path to stack definition file (can be repeated multiple times)
@@ -51,6 +51,7 @@ SILENT=false
 HELP=false
 ARGS=$*
 HUB_FILES=""
+HUB_DEPLOY_PROFILE="pod"
 dotenv=$HUB_HOME/env/dotenv
 
 if test -f ".env"; then
@@ -71,7 +72,7 @@ while [ "$1" != "" ]; do
     #   ;;             
     -r | --requirement ) 
       shift 
-      REQS=$(echo "$REQS" | xargs)
+      REQS=$(echo "$REQS $1" | xargs)
       ;;
     -S | --silent )
       SILENT=true
@@ -148,7 +149,7 @@ expand_hub_files() {
     fi
     if test -f "$f"; then
       EXPANDED=$(echo "$EXPANDED $f" | xargs)
-      echo "* File $(basename $f): exist"
+      $HELP || echo "* File $(basename $f): exist"
       included=$(yq r "$f" -j | jq -r '.extensions.include|select(.)[]')
       if test -n "$included"; then
         expand_hub_files $included
@@ -192,14 +193,20 @@ update_symlink() {
 }
 
 finalize() {
+  # shellcheck disable=SC2046
+  local profiles
+  if test -d "$WORKDIR/.hub/profiles"; then profiles="$(ls "$WORKDIR/.hub/profiles")"; fi
+  if test -d "$script_dir/profiles"; then profiles="$(ls $script_dir/profiles)"; fi
+
+  local rv=$?
   echo "Finalizing env files..."
   TEMP1=$(temp_file)
   TEMP2=$(temp_file)
 cat << EOF >> $TEMP2
   # stack definition files
   HUB_FILES="$HUB_FILES"
-  # deploy options can have value: (pod | toolbox | local)
-  HUB_DEPLOY_PROFILE="pod"
+  # deploy options can be: $profiles
+  HUB_DEPLOY_PROFILE="$HUB_DEPLOY_PROFILE"
 EOF
   MERGE_FILES="$MERGE_FILES -f $TEMP2"
   # shellcheck disable=SC2001
@@ -208,9 +215,14 @@ EOF
   echo -n "* Saving configuration to .hub/env/$HUB_DOMAIN_NAME.env: "
   $HUB_HOME/env/copy "$TEMP1" "$WORKDIR/.hub/env/$HUB_DOMAIN_NAME.env"
   update_symlink "$WORKDIR/.hub/env/$HUB_DOMAIN_NAME.env" "$WORKDIR/.env"
-  echo "Done!"
+  echo 
+  if test "$rv" = "0"; then
+    echo "Done!"
+  else
+    echo "See error above!"
+  fi
+  exit $rv
 }
-trap 'finalize' EXIT
 
 if test -z "$WORKDIR"; then
   first=$(echo "$HUB_FILES" | awk '{print $1;}')
@@ -225,7 +237,7 @@ if test ! -d $WORKDIR; then
   mkdir -p "$WORKDIR"
 fi
 
-echo "Checking hub files:"
+$HELP || echo "Checking hub files:"
 expand_hub_files $HUB_FILES
 HUB_FILES="$EXPANDED"
 mkdir -p "$WORKDIR/.hub/env"
@@ -245,9 +257,11 @@ if test -z "$ARGS" || $HELP; then
   exit
 fi
 
+trap 'finalize $?' EXIT
+
 MERGE_FILES=""
-echo "Reading .env file: "
 if test -f "$WORKDIR/.env"; then
+  echo "Reading .env file: "
   set +a
   eval $($dotenv export -f "$WORKDIR/.env" )
   set -a
@@ -273,9 +287,18 @@ for req in $(echo "$REQS" | xargs -n1); do
   fi
   TEMP=$(temp_file)
   if ! $configure --output "$TEMP" $ARGS; then
-    rv=$?
-    echo "Error: $req completed with error!"
-    exit $rv
+    cat << EOF
+
+Error: $req completed with error!
+
+For trouble shooting:
+  hub configure -r $req --verbose
+
+For additional options:
+  hub configure -r $req --help
+
+EOF
+    exit 4
   fi
   if test -s "$TEMP"; then
     set +a
diff --git a/hub-stack-deploy b/hub-stack-deploy
--- a/hub-stack-deploy
+++ b/hub-stack-deploy
@@ -1,6 +1,7 @@
 #!/bin/bash -e
 
 usage() {
+# shellcheck disable=SC2006
 cat << EOF
 
 Deploys this stack
@@ -28,7 +29,6 @@ EOF
 }
 
 FULL_STACK=true
-
 dotenv="$(dirname "$0")/env/dotenv -f .env"
 set +a
 eval "$($dotenv "export")"
@@ -124,40 +124,65 @@ export HUB_YAML HUB_FILES HUB_STATE_FILE HUB_ELABORATE_FILE
 for f in $HUB_FILES; do
   test -f $f || continue;
   BEFORE="$BEFORE $(yq r "$f" -j | jq -r '.extensions.deploy.before? | select(.)[]')"
+  AFTER="$AFTER $(yq r "$f" -j | jq -r '.extensions.deploy.after? | select(.)[]')"
 done
-if test -n "$BEFORE"; then
-  echo "Running before deployment extensions: $BEFORE"
-  for i in $(echo "$BEFORE" | xargs -n1); do
-    if test -f "$(dirname "$0")/$i/before-deploy"; then
-      "$(dirname "$0")/$i/before-deploy"
-    fi
-  done
-fi
+
+for i in $(echo "$BEFORE" | xargs -n1); do
+  if test -f "$WORKDIR/.hub/$i/before-deploy"; then
+    hook="$WORKDIR/.hub/$i/before-deploy"
+  elif test -f "$(dirname "$0")/$i/before-deploy"; then
+    hook="$(dirname "$0")/$i/before-deploy"
+  else
+    echo "Warning! cannot find before deploy hook: $i"
+    continue
+  fi
+  echo "Running before deploy: $i"
+  $hook
+done
 
 if test -z "$HUB_DEPLOY_PROFILE"; then
   HUB_DEPLOY_PROFILE=$($dotenv get "HUB_DEPLOY_PROFILE" --default "pod")
 fi
-if test ! -f "$(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/deploy"; then
-  echo "Warning: $(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/deploy not found!"
-  echo "Falling back to deployment profile: local"
-  HUB_DEPLOY_PROFILE="local"
+
+script_dir=$(dirname "$0")
+if test -f "$WORKDIR/.hub/profiles/$HUB_DEPLOY_PROFILE/deploy"; then
+  deploy="$WORKDIR/.hub/profiles/$HUB_DEPLOY_PROFILE/deploy"
+elif test -f "$script_dir/profiles/$HUB_DEPLOY_PROFILE/deploy"; then
+  deploy="$script_dir/profiles/$HUB_DEPLOY_PROFILE/deploy"
+else
+  # shellcheck disable=SC2046
+  if test -d "$WORKDIR/.hub/profiles"; then profiles="$(ls "$WORKDIR/.hub/profiles")"; fi
+  if test -d "$script_dir/profiles"; then profiles="$(ls $script_dir/profiles)"; fi
+  cat << EOF
+
+Error! Cannot find deployment profile $HUB_DEPLOY_PROFILE
+* Not found: $WORKDIR/.hub/profiles/$HUB_DEPLOY_PROFILE/deploy
+* Not found: $script_dir/profiles/$HUB_DEPLOY_PROFILE/deploy
+
+Deployment profile configured via .env variable HUB_DEPLOY_PROFILE
+
+Currently supported profiles: $(echo "$profiles" | xargs)
+
+Completed with errors!
+EOF
+  exit 5
 fi
 
+echo "Using deployment profile: $HUB_DEPLOY_PROFILE"
 # shellcheck disable=SC2086,SC2046
-$(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/deploy \
-  "$HUB_ELABORATE_FILE" \
-  -s "$HUB_STATE_FILE" \
-  $HUB_DEPLOY_OPTS
-
-for f in $HUB_FILES; do
-  test -f "$f" || continue;
-  AFTER="$AFTER $(yq r "$f" -j | jq -r '.extensions.deploy.after? | select(.)[]')"
+$deploy  "$HUB_ELABORATE_FILE" -s "$HUB_STATE_FILE" $HUB_DEPLOY_OPTS
+for i in $(echo "$AFTER" | xargs -n1); do
+  if test -f "$WORKDIR/.hub/$i/after-deploy"; then
+    hook="$WORKDIR/.hub/$i/after-deploy"
+  elif test -f "$(dirname "$0")/$i/after-deploy"; then
+    hook="$(dirname "$0")/$i/after-deploy"
+  else
+    echo "Warning! cannot find post hook: $i"
+    continue
+  fi
+  echo "Running after deploy hook: $i"
+  $hook
 done
-if test -n "$AFTER"; then
-  echo "Running post deployment extensions: $AFTER"
-  for i in $(echo "$AFTER" | xargs -n1); do
-    if test -f "$(dirname "$0")/$i/after-deploy"; then
-      "$(dirname "$0")/$i/after-deploy"
-    fi
-  done
-fi
+
+echo 
+echo "Done!"
diff --git a/hub-stack-undeploy b/hub-stack-undeploy
--- a/hub-stack-undeploy
+++ b/hub-stack-undeploy
@@ -91,50 +91,71 @@ fi
 
 cat <<EOF
 
-### Proceeding with undeploy "$HUB_DOMAIN_NAME"
-
+Proceeding with undeploy "$HUB_DOMAIN_NAME"
 EOF
 
-if test -z "$HUB_DEPLOY_PROFILE"; then
-  HUB_DEPLOY_PROFILE=$($dotenv get "HUB_DEPLOY_PROFILE")
-  if test -z "$HUB_DEPLOY_PROFILE"; then
-    HUB_DEPLOY_PROFILE="pod"
-  fi
-fi
-if test ! -f "$(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/undeploy"; then
-  echo "Warning: $(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/undeploy not found!"
-  echo "Falling back to $(dirname "$0")/profiles/local/undeploy"
-  HUB_DEPLOY_PROFILE="local"
-fi
-
 for f in $HUB_FILES; do
-  test -f "$f" || continue;
-  AFTER="$AFTER $(yq r "$f" -j | jq -r '.extensions.undeploy.before? | select(.)[]')"
-done
-if test -n "$AFTER"; then
-  echo "Running post deployment extensions: $AFTER"
-  for i in $(echo "$AFTER" | xargs -n1); do
-    if test -f "$(dirname "$0")/$i/before-undeploy"; then
-      "$(dirname "$0")/$i/before-undeploy"
-    fi
-  done
-fi
-
-# shellcheck disable=SC2086,SC2046
-$(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/undeploy \
-  "$HUB_ELABORATE_FILE" \
-  -s "$HUB_STATE_FILE" \
-  $HUB_OPTS
-
-for f in $HUB_FILES; do
-  test -f "$f" || continue;
+  test -f $f || continue;
+  BEFORE="$BEFORE $(yq r "$f" -j | jq -r '.extensions.undeploy.before? | select(.)[]')"
   AFTER="$AFTER $(yq r "$f" -j | jq -r '.extensions.undeploy.after? | select(.)[]')"
 done
-if test -n "$AFTER"; then
-  echo "Running post deployment extensions: $AFTER"
-  for i in $(echo "$AFTER" | xargs -n1); do
-    if test -f "$(dirname "$0")/$i/after-undeploy"; then
-      "$(dirname "$0")/$i/after-undeploy"
-    fi
-  done
+
+for i in $(echo "$BEFORE" | xargs -n1); do
+  if test -f "$WORKDIR/.hub/$i/before-undeploy"; then
+    hook="$WORKDIR/.hub/$i/before-undeploy"
+  elif test -f "$(dirname "$0")/$i/before-undeploy"; then
+    hook="$(dirname "$0")/$i/before-undeploy"
+  else
+    echo "Warning! cannot find before undeploy hook: $i"
+    continue
+  fi
+  echo "Running before undeploy hook: $i"
+  $hook
+done
+
+if test -z "$HUB_DEPLOY_PROFILE"; then
+  HUB_DEPLOY_PROFILE=$($dotenv get "HUB_DEPLOY_PROFILE" --default "pod")
 fi
+
+script_dir=$(dirname "$0")
+if test -f "$WORKDIR/.hub/profiles/$HUB_DEPLOY_PROFILE/undeploy"; then
+  undeploy="$WORKDIR/.hub/profiles/$HUB_DEPLOY_PROFILE/undeploy"
+elif test -f "$script_dir/profiles/$HUB_DEPLOY_PROFILE/undeploy"; then
+  undeploy="$script_dir/profiles/$HUB_DEPLOY_PROFILE/undeploy"
+else
+  # shellcheck disable=SC2046
+  if test -d "$WORKDIR/.hub/profiles"; then profiles="$(ls "$WORKDIR/.hub/profiles")"; fi
+  if test -d "$script_dir/profiles"; then profiles="$(ls $script_dir/profiles)"; fi
+  cat << EOF
+
+Error! Cannot find deployment profile $HUB_DEPLOY_PROFILE
+* Not found: $WORKDIR/.hub/profiles/$HUB_DEPLOY_PROFILE/undeploy
+* Not found: $script_dir/profiles/$HUB_DEPLOY_PROFILE/undeploy
+
+Deployment profile configured via .env variable HUB_DEPLOY_PROFILE
+
+Currently supported profiles: $(echo "$profiles" | xargs)
+
+Completed with errors!
+EOF
+  exit 5
+fi
+
+echo "* Using deployment profile: $HUB_DEPLOY_PROFILE"
+$undeploy "$HUB_ELABORATE_FILE" $HUB_OPTS 
+
+for i in $(echo "$AFTER" | xargs -n1); do
+  if test -f "$WORKDIR/.hub/$i/after-undeploy"; then
+    hook="$WORKDIR/.hub/$i/after-undeploy"
+  elif test -f "$(dirname "$0")/$i/after-undeploy"; then
+    hook="$(dirname "$0")/$i/after-undeploy"
+  else
+    echo "Warning! cannot find after undeploy hook: $i"
+    continue
+  fi
+  echo "Running after undeploy hook: $i"
+  $hook
+done
+
+echo 
+echo "Done!"
