`hub-vault`: better retry optioins

diff --git a/hub-vault b/hub-vault
--- a/hub-vault
+++ b/hub-vault
@@ -35,7 +35,7 @@ EOF
 context="_"
 namespace="vault"
 VAULT_SVC="svc/vault"
-SILENT=false
+SILENT=${SILENT:-false}
 VAULT_ARGS=
 
 # shellcheck disable=SC1091
@@ -52,10 +52,10 @@ while [ "$1" != "" ]; do
     -c | --kubecontext )    shift
                             context="$1"
                             ;;
+    --current-kubecontext ) context="_"
+                            ;;
     -S | --service )        shift
                             VAULT_SVC="$1"
-                            ;;
-    --current-kubecontext ) context="_"
                             ;;
     -s | --silent )         SILENT=true
                             ;;
@@ -100,16 +100,40 @@ VAULT_PORT=$(echo $SERVICE_PAYLOAD \
             )
 
 connect() {
-  $SILENT || echo "* Port forwarding to $1"
-  $KUBECTL port-forward "$VAULT_SVC" "$1:$VAULT_PORT" >/dev/null 2>&1 & 
-  trap 'kill $(jobs -p)' EXIT
-  sleep 3
+  trap 'kill $(jobs -p) || exit 0' EXIT
+  $SILENT || echo -n "* Starting port forwarding to $1: "
+  success=false
+  kfctl_pid=0
+  for _ in $(seq 30); do
+    $SILENT || echo -n "."
+    if ! ps -p $kfctl_pid > /dev/null; then
+      $KUBECTL port-forward "$VAULT_SVC" "$1:$VAULT_PORT" >/dev/null 2>&1 &
+      kfctl_pid=$!
+      sleep 2
+      continue
+    fi
+
+    if curl -sLko /dev/null "$VAULT_ADDR/v1/sys/health"; then
+      success=true
+      break
+    fi
+    sleep 5
+  done
+
+  if ! $success; then
+    $SILENT || echo " Error"
+    $SILENT || echo "Timed out trying to establish port forwarding to vault"
+    exit 1
+  fi
+  $SILENT || echo " Done"
 }
 
 $SILENT || echo ":$VAULT_PORT"
 connect "$VAULT_LOCAL_PORT"
 $SILENT || echo -n "* Checking vault at $VAULT_ADDR: "
-statuscode=$(curl -sLko /dev/null -w "%{http_code}" $VAULT_ADDR/v1/sys/health)
+
+# see: https://www.vafultproject.io/api-docs/system/health#read-health-information
+statuscode=$(curl -sLko /dev/null -w "%{http_code}" "$VAULT_ADDR/v1/sys/health")
 case "$statuscode" in
 "200" )
   STATUS="Running" ;;
@@ -128,10 +152,7 @@ case "$statuscode" in
 *)
   STATUS="Status code $statuscode" ;;
 esac
-
 $SILENT || echo "$STATUS"
-
-$SILLENT || echo "* Running: vault $VAULT_ARGS"
-
+$SILENT || echo "* Running: vault $VAULT_ARGS"
 # shellcheck disable=SC2086
 vault $VAULT_ARGS
