Introduce to use helm chart with local tarballs or charts as a dir

diff --git a/hub-component-helm-deploy b/hub-component-helm-deploy
--- a/hub-component-helm-deploy
+++ b/hub-component-helm-deploy
@@ -1,19 +1,75 @@
-#!/bin/bash
-
-if test -z "$COMPONENT_NAME" -o -z "$DOMAIN_NAME" -o -z "$NAMESPACE" -o -z "$HELM_REPO" -o -z "$HELM_CHART"; then
-    echo "COMPONENT_NAME, DOMAIN_NAME, NAMESPACE, HELM_REPO, HELM_CHART must be set"
-    exit 1
+#!/bin/bash -e
+if test -z "$COMPONENT_NAME" -o -z "$DOMAIN_NAME" -o -z "$NAMESPACE" -o -z "$HELM_CHART"; then
+#  -o -z "$HELM_REPO"
+    echo "COMPONENT_NAME, DOMAIN_NAME, NAMESPACE, HELM_CHART must be set"
 fi
 
-if test -n "$HELM_CHART_VERSION"; then
-    chart_version="--version $HELM_CHART_VERSION"
-fi
-
-helm3=helm
+charts=".charts"
+yq="yq"
+helm3="helm"
 if which helm3 >/dev/null; then helm3=helm3; fi
 
 export kubectl="kubectl --context=$DOMAIN_NAME --namespace=$NAMESPACE"
 export helm="$helm3 --kube-context=$DOMAIN_NAME --namespace=$NAMESPACE"
+
+rm -rf $charts
+mkdir -p $charts
+
+echo "Resolving helm chart: $HELM_CHART"
+if test -d "$HELM_CHART"; then
+    chart_path="$HELM_CHART"
+    echo "* From directory: $chart_path"
+elif test -d "charts/$HELM_CHART"; then
+    chart_path="charts/$HELM_CHART"
+    echo "* From directory: $chart_path"
+elif test -f "$HELM_CHART"; then
+    echo "* From tarball: $HELM_CHART"
+    tar xzf "$HELM_CHART" -C "$charts"
+    dir=$(tar tf "$HELM_CHART" | grep Chart.yaml | head -n1 | cut -d "/" -f1)
+    chart_path="$charts/$dir"
+elif test -f "charts/$HELM_CHART"; then
+    echo "* From tarball: $HELM_CHART"
+    tar xzf "charts/$HELM_CHART" -C "$charts"
+    dir=$(tar tf "charts/$HELM_CHART" | grep Chart.yaml | head -n1 | cut -d "/" -f1)
+    chart_path="$charts/$dir"
+elif test -d "charts"; then
+    echo "* From metadata: $HELM_CHART $HELM_CHART_VERSION"
+    for file in charts/*.tgz; do
+        if test ! -f "$file"; then continue; fi;
+        echo "  chart: $file"
+        _name=$(helm show chart "$file" | yq e -M '.name' -)
+        _ver=$(helm show chart "$file" | yq e -M '.version' -)
+        echo "  name: $_name version: $_ver"
+        if test "$_name" = "$HELM_CHART"; then
+            if test -z "$HELM_CHART_VERSION" -o "$HELM_CHART_VERSION" = "$_ver"; then
+                echo "  resolved to: $file"
+                if test -d "$file"; then
+                    chart_path="$file"
+                elif test -f "$file"; then
+                    tar xzf "$file" -C "$charts"
+                    dir=$(tar tf "$HELM_CHART" | grep Chart.yaml | head -n1 | cut -d "/" -f1)
+                    chart_path="$charts/$dir"
+                    break
+                fi
+            fi
+        fi
+    done
+elif test -n "$HELM_REPO"; then
+    echo "Fetching chart repository: $HELM_REPO"
+    $helm repo add stable "https://charts.helm.sh/stable"
+    $helm repo add "$COMPONENT_NAME" "$HELM_REPO"
+    $helm repo update
+    if test -n "$HELM_CHART_VERSION"; then
+        HELM_ARGS="$HELM_ARGS --version $HELM_CHART_VERSION"
+    fi
+    # shellcheck disable=SC2086
+    $helm fetch "$COMPONENT_NAME/$HELM_CHART" $HELM_ARGS --destination $charts --untar
+    chart_path=$charts/$(basename "$HELM_CHART")
+else
+    echo "Cannot find helm chart $HELM_CHART"
+    exit 1
+fi
+
 
 # TODO no HELM_HOME in Helm 3
 # https://helm.sh/docs/faq/#xdg-base-directory-support
@@ -25,35 +81,62 @@ export helm="$helm3 --kube-context=$DOMAIN_NAME --namespace=$NAMESPACE"
 
 charts=.charts
 
-set -xe
-
-rm -rf $charts
-mkdir -p $charts
-
-if $helm list --failed --pending -q | grep -E "^$COMPONENT_NAME\$"; then
-	  $helm uninstall $COMPONENT_NAME
+echo "Checking namespace: $NAMESPACE"
+if ! $kubectl get namespace "$NAMESPACE" -o name > /dev/null;  then
+  $kubectl create namespace "$NAMESPACE"
 fi
 
-$helm repo add stable https://charts.helm.sh/stable
-$helm repo add $COMPONENT_NAME $HELM_REPO
-$helm repo update
-$helm fetch $COMPONENT_NAME/$HELM_CHART --destination $charts --untar $chart_version
-
 if test -x pre-deploy; then
+    echo "Running pre-deploy..."
     pre_deploy=$(./pre-deploy)
     helmvars=$(grep -E '^export ' <<<"$pre_deploy" || exit 0)
     if test -n "$helmvars"; then eval "$helmvars"; fi
 fi
 
-set +x
-for v in values.yaml values-*.yaml; do
-    if test -f $v; then values="$values --values $v"; fi
-done
-set -x
+if test -d "crds"; then
+    echo "Resolving CRDs"
+    for file in crds/*.yaml crds/*.yml; do
+        if test ! -f "$file"; then continue; fi
+        echo "* Reading: $file"
+        max_di=$($yq e 'di' "$file" | tail -1)
+        for i in $(seq 0 "$max_di"); do
+            crd=$($yq e "select(di == $i).metadata.name" "$file")
+            if test -z "$crd" -o "$crd" = "null"; then
+                continue
+            fi
+            if $kubectl get crd "$crd" > /dev/null; then
+                echo "  $crd already exists"
+            else
+                $kubectl create -f "$file"
+            fi
+        done
+    done
+fi
 
-$helm upgrade $COMPONENT_NAME $charts/$(basename $HELM_CHART) \
-    --install --create-namespace --wait $chart_version $values $HELM_OPTS
+if $helm list --failed --pending -q | grep -E "^$COMPONENT_NAME\$"; then
+    echo "Uninstalling chart: $COMPONENE_NAME"
+    set -x
+    $helm uninstall "$COMPONENT_NAME"
+    set +x
+fi
+
+echo "Resolving helm chart values:"
+for file in values.yaml values-*.yaml values.yml values-*.yml; do
+    if test ! -f "$file"; then continue; fi
+    echo "* $file"
+    HELM_ARGS="$HELM_ARGS --values $file";
+done
+echo "Installing helm chart: $COMPONENT_NAME"
+set -x
+# shellcheck disable=SC2086
+$helm upgrade "$COMPONENT_NAME" "$chart_path" \
+    $HELM_ARGS \
+    --install \
+    --create-namespace \
+    --wait
+set +x
 
 if test -x post-deploy; then
+    echo "Running post-deploy..."
     ./post-deploy
 fi
