Hardening around edge cases with dns renewal

diff --git a/aws/configure b/aws/configure
--- a/aws/configure
+++ b/aws/configure
@@ -35,9 +35,10 @@ while [ "$1" != "" ]; do
     --aws-profile )     shift
                         AWS_PROFILE="$1"
                         ;;
-    --dns-new )         ACTION="new"
+    --dns-new )         HUB_DOMAIN_NAME=""
+                        HUB_DOMAIN_SECRET=""
                         ;;
-    --dns-update )      ACTION="update"
+    --dns-update )      DNS_ACTION="update"
                         ;;
     --dry-run )         DRY_RUN=true
                         ;;                 
@@ -61,11 +62,36 @@ if test -z "$DOT_ENV"; then
 fi
 
 dotenv="$(dirname $(dirname $0))/env/dotenv -f $DOT_ENV"
+updateBubbleDNS() {
+  local domain secret
+  domain="$1"
+  secret="$2"
+  if test -z "$domain"; then
+    echo "Error: cannot find configuration 'domain name'"
+    exit 1
+  fi
+  if test -z "$secret"; then
+    secret=$($dotenv get "HUB_DOMAIN_SECRET")
+    if test -z "$secret"; then
+      echo "Error: cannot find configuration 'dns secret key'"
+    fi
+    exit 1
+  fi
+  echo -n "* Sending request to update $HUB_DOMAIN_NAME record: "
+  $(dirname $(dirname "$0"))/bubble-dns/update --domain-name "$domain" --secret-key "$secret"
+}
+
+if test "$DNS_ACTION" = "update"; then
+  updateBubbleDNS "$HUB_DOMAIN_NAME" "$HUB_DOMAIN_SECRET"
+  exit $?
+fi
+ 
 if test -z "$HUB_DOMAIN_NAME"; then
   echo "Configuring Bubble DNS"
   $(dirname $(dirname "$0"))/bubble-dns/new --output "$DOT_ENV" $FLAGS
   # Reading newly generated domain name by script above
   HUB_DOMAIN_NAME=$($dotenv get "HUB_DOMAIN_NAME")
+  HUB_DOMAIN_SECRET=$($dotenv get "HUB_DOMAIN_SECRET")
   if test -z "$HUB_DOMAIN_NAME"; then
     echo "Error: cannot find domain name: [$HUB_DOMAIN_NAME]"
     exit 1
@@ -135,13 +161,7 @@ HUB_STATE_REGION="$STATE_REGION"
 EOF
 
 if ! $DRY_RUN; then
-  echo -n "* Sending request to update $HUB_DOMAIN_NAME record: "
-  if test -z "$HUB_DOMAIN_SECRET"; then
-    HUB_DOMAIN_SECRET=$($dotenv get "HUB_DOMAIN_SECRET")
-  fi
-  $(dirname $(dirname "$0"))/bubble-dns/update \
-    --domain-name "$HUB_DOMAIN_NAME" \
-    --secret-key "$HUB_DOMAIN_SECRET"
+  updateBubbleDNS "$HUB_DOMAIN_NAME" "$HUB_DOMAIN_SECRET"
   cat << EOF
 * DNS record has time to live: 72 hours (refresh before expires)
 
