Style and formatting

diff --git a/aws/configure b/aws/configure
--- a/aws/configure
+++ b/aws/configure
@@ -10,7 +10,7 @@ AWS parameters:
   --domain-name              Custom DNS domain name under existing base domain
   --base-domain-aws-profile  AWS Profile for base domain (in case base domain
                                  hosted zone is located in another AWS account)
-  --prefer-local             Deploy state locally only
+  --prefer-local             Save deployment state locally only
 
 Bubble DNS parameters:
   --dns-update  Request to update DNS registration
@@ -69,7 +69,7 @@ if test $VERBOSE = "true"; then
 fi
 
 if test -z "$DOT_ENV"; then
-  echo "Error: please run with option: $(dirname "0")/$(basename "0") --output FILE "
+  echo "Error: please run with option: $0 --output FILE"
   exit 2
 fi
 
@@ -225,22 +225,18 @@ if test -z "$HUB_STATE"; then
   echo "* Setting default location for hub state file"
   STACK=${STACK:-$(basename "$(pwd)")}
   HUB_STATE_FILE=".hub/$HUB_DOMAIN_NAME.state"
-  if $PREFER_LOCAL_STATE; then
-    $dotenv set "HUB_STATE=\"$HUB_STATE_FILE\""
-  else
-    HUB_STATE_S3="s3://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/$STACK/hub.state"
-    $dotenv set "HUB_STATE=\"$HUB_STATE_FILE,$HUB_STATE_S3\""
+  if ! $PREFER_LOCAL_STATE; then
+    HUB_STATE_FILE="$HUB_STATE_FILE,s3://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/$STACK/hub.state"
   fi
+  $dotenv set "HUB_STATE=\"$HUB_STATE_FILE\""
 fi
 
 if test -z "$HUB_ELABORATE"; then
   echo "* Setting default location for hub elaborate file"
   STACK=${STACK:-$(basename "$(pwd)")}
   HUB_ELABORATE_FILE=".hub/$HUB_DOMAIN_NAME.elaborate"
-  if $PREFER_LOCAL_STATE; then
-    $dotenv set "HUB_ELABORATE=\"$HUB_ELABORATE_FILE\""
-  else
-    HUB_ELABORATE_S3="s3://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/$STACK/hub.elaborate"
-    $dotenv set "HUB_ELABORATE=\"$HUB_ELABORATE_FILE,$HUB_ELABORATE_S3\""
+  if ! $PREFER_LOCAL_STATE; then
+    HUB_ELABORATE_FILE="$HUB_ELABORATE_FILE,s3://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/$STACK/hub.elaborate"
   fi
+  $dotenv set "HUB_ELABORATE=\"$HUB_ELABORATE_FILE\""
 fi
