Reporting function installation

diff --git a/gcp/configure b/gcp/configure
--- a/gcp/configure
+++ b/gcp/configure
@@ -28,15 +28,10 @@ while [ "$1" != "" ]; do
     --gcp-project-id)
         shift
         GOOGLE_PROJECT="$1"
+        ;;     
+    --force)
+        FORCE_FUNCTION_UPDATE=1
         ;;
-    # --gcp-region)
-    #     shift
-    #     GOOGLE_REGION="$1"
-    #     ;;
-    # --gcp-zone)
-    #     shift
-    #     GOOGLE_ZONE="$1"
-    #     ;;
     --domain-name)
         shift
         HUB_DOMAIN_NAME="$1"
@@ -124,6 +119,32 @@ gsutil label ch -l "managed-by":"superhub" "gs://$HUB_STATE_BUCKET" > /dev/null 
 
 HUB_STATE_FILE=".hub/$HUB_DOMAIN_NAME.state,gs://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/hub.state"
 HUB_ELABORATE_FILE=".hub/$HUB_DOMAIN_NAME.elaborate,gs://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/hub.elaborate"
+
+### Usage reporting function
+USAGE_REPORTING_FUNCTION_REGION="us-central1"
+USAGE_REPORTING_FUNCTION_REPO="https://github.com/agilestacks/hub-state.git"
+USAGE_REPORTING_FUNCTION_REF="master"
+USAGE_REPORTING_FUNCTION_NAME="reporting-$(echo "$HUB_STATE_BUCKET" | tr '[:upper:]' '[:lower:]')"
+echo "Configuring usage reporting cloud function "
+if gcloud functions describe "$USAGE_REPORTING_FUNCTION_NAME" --region "$USAGE_REPORTING_FUNCTION_REGION" > /dev/null 2>&1 && test -z "$FORCE_FUNCTION_UPDATE"; then
+  echo "* Usage reporting cloud function already deployed to $GOOGLE_PROJECT for $HUB_STATE_BUCKET. Use --force flag to redeploy"
+else
+  echo -n "* Deploying the function to $GOOGLE_PROJECT, subscribing for $HUB_STATE_BUCKET events (it could take up to 2 minutes). "
+  TEMP_DIR_REPORTING=$(mktemp -d || exit 2)
+  mkdir -p "$TEMP_DIR_REPORTING"
+  trap 'rm -rf $TEMP_DIR_REPORTING' EXIT
+  git clone --depth 1 "$USAGE_REPORTING_FUNCTION_REPO" "$TEMP_DIR_REPORTING" > /dev/null 2>&1
+  git -C "$TEMP_DIR_REPORTING" checkout "$USAGE_REPORTING_FUNCTION_REF" > /dev/null 2>&1
+  if RESULT=$(gcloud functions deploy "$USAGE_REPORTING_FUNCTION_NAME" --runtime nodejs16 \
+    --trigger-bucket gs://"$HUB_STATE_BUCKET" \
+    --source "$TEMP_DIR_REPORTING"/api --entry-point reporting 2>&1); then
+    echo "Deployed"
+  else
+    color err "Error occured, see the details below:"
+    color err "$RESULT"
+    exit 1
+  fi
+fi
 
 ### State function
 STATE_FUNCTION_REGION="us-central1"
