Extensions performance and other fine tunings

diff --git a/env/configure b/env/configure
--- a/env/configure
+++ b/env/configure
@@ -46,6 +46,8 @@ if test -z "$HUB_WORKDIR"; then
   export HUB_WORKDIR
 fi
 
+jq="jq -cMr"
+
 HISTORY_FILE="$HUB_WORKDIR/.hub/env/.history"
 mkdir -p "$(dirname "$HISTORY_FILE")"
 touch "$HISTORY_FILE"
@@ -61,15 +63,15 @@ if test -z "$HUB_FILES"; then
 fi
 
 echo "Configuring environment variables"
-ALL_ENVS=
-for f in $HUB_FILES; do
-  test -f "$f" || continue;
-  envs=$(
-    yq e $f -o=json | jq -cr \
-      '.. | objects | with_entries(select(.key=="fromEnv")).fromEnv? | select(.!=null)'
-  )
-  ALL_ENVS="$ALL_ENVS $envs"
-done
+# ALL_ENVS=
+# for f in $HUB_FILES; do
+#   test -f "$f" || continue;
+#   envs=$(
+#     yq e $f -o=json | jq -cr \
+#       '.. | objects | with_entries(select(.key=="fromEnv")).fromEnv? | select(.!=null)'
+#   )
+#   ALL_ENVS="$ALL_ENVS $envs"
+# done
 
 if test -z "$DOT_ENV"; then
   echo "Error: please run with option: $(dirname "0")/$(basename "0") --output FILE "
@@ -118,11 +120,16 @@ getParamNameByEnvVar() {
 }
 
 touch $DOT_ENV
-for ENV in $(echo $ALL_ENVS | xargs -n 1 | sort -u); do
+for ENV in $(params listenv); do
+  json=$(params envvar "$ENV")
+  if test -z "$json"; then
+    color warn "* Warning: cannot find parameter for variable: $ENV"
+    continue
+  fi
+
   VALUE=$(printenv "$ENV" || echo "")
-  PARAM=$(getParamNameByEnvVar "$ENV")
-  BRIEF=$(getByEnvVar "brief" "$ENV")
-  EMPTY="$(getByEnvVar "empty" "$ENV")"
+  PARAM=$(echo "$json" | $jq '.name  | select (.)')
+  BRIEF=$(echo "$json" | $jq '.brief | select (.)')
   if test -z "$VALUE"; then
     echo -n "* Parameter: "
     color h "$PARAM"
@@ -134,6 +141,7 @@ for ENV in $(echo $ALL_ENVS | xargs -n 1 | sort -u); do
     VAL_history=$($history get $ENV)
     VAL_random=$(uuidgen | tr '[:upper:]' '[:lower:]' | tr -d -)
     VAL_empty=""
+    EMPTY=$(echo "$json" | $jq '.empty | select (.)')
     if test "$EMPTY" = "allow"; then
       HASHTAGS="hubstate default empty"
     else
diff --git a/hub-show b/hub-show
--- a/hub-show
+++ b/hub-show
@@ -11,7 +11,7 @@ usage()
 {
 cat << EOF
 Print info about stack in JSON format. Stack parameters and outputs are merged by default with the precedence to the outputs. Execute current script with parameter "-o" to see outputs separately
-Usage: $(basename "$0") -s STACK_DOMAIN [-o] [-t]
+Usage: $HUB_EXTENSION -s STACK_DOMAIN [-o] [-t]
 Parameters:
     -s --stack      domain name of the stack
     -o --split      split stack outpus from parameters
@@ -74,33 +74,40 @@ while [ "$1" != "" ]; do
 done
 
 if test -z "$HUB_TOKEN"; then
-  RESP=$(hub explain "${HUB_STATE:-.hub/$HUB_DOMAIN_NAME.state}" --json || true) # this will spill into stderr on error
+  RESP=$(hub explain "${HUB_STATE:-.hub/$HUB_DOMAIN_NAME.state}" --json || echo "") # this will spill into stderr on error
   if test -z "$RESP"; then
-    if test -z "$KUBECONFIG" -a -n "$HUB_KUBECONFIG" -a -e "$HUB_KUBECONFIG"; then
-      export KUBECONFIG=$HUB_KUBECONFIG
+    if test -z "$HUB_FILES"; then
+      HUB_FILES="$(dotenv get HUB_FILES)"
     fi
-    ns="kube-system"
-    cm="superhub"
-    kubectl="kubectl -n $ns -o json"
-    if ! $kubectl get configmap "superhub" > /dev/null 2>&1; then
-      echo "Error: no stack deployed" 1>&2
-      exit 5
-    fi
-    if test -z "$HUB_DOMAIN_NAME"; then
-      HUB_DOMAIN_NAME=$( \
-        $kubectl get configmap $cm \
-        | jq -r '.data|keys[0]|select(.)'
-      )
-      if test -z "$HUB_DOMAIN_NAME"; then
-        echo "Error: cannot find stack data" 1>&2
-        exit 4
+
+    has_inventory_configmap="$(yq -N e '[ .extensions.deploy.after ] | select(. == "inventory-configmap")' $HUB_FILES)"
+    if test -n "$has_inventory_configmap"; then
+      if test -z "$KUBECONFIG" -a -n "$HUB_KUBECONFIG" -a -e "$HUB_KUBECONFIG"; then
+        export KUBECONFIG=$HUB_KUBECONFIG
       fi
+      ns="kube-system"
+      cm="superhub"
+      kubectl="kubectl -n $ns -o json"
+      if ! $kubectl get configmap "superhub" > /dev/null 2>&1; then
+        >&2 echo "Error: no stack deployed"
+        exit 5
+      fi
+      if test -z "$HUB_DOMAIN_NAME"; then
+        HUB_DOMAIN_NAME=$( \
+          $kubectl get configmap $cm \
+          | jq -r '.data|keys[0]|select(.)'
+        )
+        if test -z "$HUB_DOMAIN_NAME"; then
+          >&2 echo "Error: cannot find stack data"
+          exit 4
+        fi
+      fi
+      RESP=$( \
+        $kubectl get configmap $cm | \
+        jq -r ".data[\"$HUB_DOMAIN_NAME\"] | select(.)" | \
+        base64 -d
+      )
     fi
-    RESP=$( \
-      $kubectl get configmap $cm | \
-      jq -r ".data[\"$HUB_DOMAIN_NAME\"] | select(.)" | \
-      base64 -d
-    )
   fi
 else
   RESP=$(hub api instance get -j \
